import re

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    replacements = [
        # UI Options
        ('"fur cap"', '"毛皮帽"'),
        ('"slippers"', '"拖鞋"'),
        ('"provisions"', '"補給品"'),
        ('"Moonshade"', '"月影城"'),
        ('"Batlin"', '"巴特林"'),
        ('"letter"', '"信件"'),
        ('"storms"', '"風暴"'),
        ('"Goblins"', '"哥布林"'),
        ('"bye"', '"告辭"'),
        ('"daughter"', '"女兒"'),
        ('"colors"', '"顏色"'),
        ('"results"', '"結果"'),
        ('"change subject"', '"改變話題"'),
        ('"Alyssand"', '"Alyssand"'),
        ('"Keth"', '"Keth"'),
        ('"engagement ring"', '"訂婚戒指"'),
        ('"not return"', '"沒回來"'),
        ('"ring"', '"戒指"'),
        ('"Filari"', '"菲拉利幣"'),
        ('"two reasons"', '"兩個原因"'),
        ('"unsafe"', '"不安全"'),
        ('"Freli"', '"Freli"'),
        ('"Elissia"', '"Elissia"'),
        ('"healer"', '"治療師"'),
        ('"horticulturist"', '"園藝師"'),
        ('"Seth"', '"Seth"'),
        ('"Delphynia"', '"黛爾菲妮亞"'),
        ('"Fawn Tower"', '"幼鹿塔"'),
        ('"Pomdirgun"', '"Pomdirgun"'),
        ('"Magister"', '"大師"'),
        ('"Monitor"', '"蒙利多城"'),
        ('"highwaymen"', '"攔路強盜"'),

        # Messages
        ('"@Excuse me, sir.@"', '"@打擾一下，先生。@"'),
        ('"@Do I know thee?@"', '"@我認識你嗎？@"'),
        ('"\\"Unless thou bearest word from my son, I will not bother with thee! Go back to Fedabiblio and tell him I have no business with the affairs of Mages!\\""', '"「除非你帶來了我兒子的消息，否則我不想理你！回去告訴 Fedabiblio，我對法師的事務沒有興趣！」"'),
        ('"\\"I cannot understand why Monitorians prefer their women scarred.\\""', '"「我無法理解為什麼蒙利多城( Monitor )的人會喜歡他們的女人的臉上有疤痕。」"'),
        ('"\\"Forgive me... I am forgetting myself. I am... ah...\\""', '"「原諒我……我忘了我自己。我是……啊……」"'),
        ('"\\"I am Delin, Fawn\'s provisioner. How may I serve thee, lady Pikeman?\\""', '"「我是 Delin，幼鹿城( Fawn )的補給商。長槍兵( Pikeman )女士，我能為妳效勞嗎？」"'),
        ('"\\"I do not recall seeing thy face among the Fawn Tower garrison. Have I met thee? I regret I cannot remember...\\""', '"「我不記得在幼鹿塔( Fawn Tower )的守軍中見過你的臉。我們見過嗎？很遺憾我記不起來了……」"'),
        ('"\\"I am Delin, Fawn\'s provisioner. Forgive me if thou dost already know me...\\""', '"「我是 Delin，幼鹿城( Fawn )的補給商。如果你已經認識我了，請原諒我……」"'),
        ('"\\"How may I serve thee, noble Pikeman?\\""', '"「高貴的長槍兵( Pikeman )，我能為你效勞嗎？」"'),
        ('"\\"Ah... art thou one of my daughter\'s friends? I cannot seem to recall thee...\\""', '"「啊……妳是我女兒的朋友嗎？我好像不記得妳了……」"'),
        ('"\\"I am Delin, Fawn\'s provisioner. Is there something I can do for thee?\\""', '"「我是 Delin，幼鹿城( Fawn )的補給商。有什麼我可以為妳效勞的嗎？」"'),
        ('"\\"Hast thou need of my services, "', '"「你需要我的服務嗎， "'),
        ('"? Or art thou here to court my daughter? I fear I cannot recall...\\""', '"？還是你是來追求我女兒的？恐怕我記不起來了……」"'),
        ('"\\"I am Delin, provisioner of Fawn. In case we have not been introduced.\\""', '"「我是 Delin，幼鹿城( Fawn )的補給商。以防我們還沒互相介紹過。」"'),
        ('"\\"\'Tis a nice fur cap, "', '"「這是一頂很棒的毛皮帽， "'),
        ('". If thou dost wish more, I fear thou wilt have to venture to Monitor thyself. Though I have forgotten the maker\'s name at this time...\\""', '"。如果你想要更多，恐怕你得自己去蒙利多城( Monitor )一趟。雖然我現在忘記了製造者的名字……」"'),
        ('"\\"I have not had a supply wagon bring arms or furs in a score of days. \'Tis the storms!\\""', '"「我已經有二十多天沒有補給車運送武器或毛皮來了。都是因為這些風暴！」"'),
        ('"\\"I fear I have no more fur caps in stock, "', '"「恐怕我沒有毛皮帽的庫存了， "'),
        ('". I fear thou wilt have to venture to Monitor thyself, if thou dost wish one.\\tThough I have forgotten the maker\'s name at this time...\\""', '"。如果你想要一頂，恐怕你得自己去蒙利多城( Monitor )一趟。雖然我現在忘記了製造者的名字……」"'),
        ('"\\"Fine slippers, though well-worn. Not something that thou wouldst find here, "', '"「很精緻的拖鞋，雖然穿得很舊了。這不是你能在這裡找到的東西， "'),
        ('".\\""', '"。」"'),
        ('"\\"Such frail things would be quickly ruined by the cold and wet here in Fawn... Just like my poor Elissia...\\""', '"「這種脆弱的東西在幼鹿城( Fawn )的寒冷潮濕中很快就會毀掉……就像我可憐的 Elissia 一樣……」"'),
        ('"\\"I have never carried slippers, "', '"「我從來沒有賣過拖鞋， "'),
        ('", though my poor Elissia yearned for them so.\\""', '"，雖然我可憐的 Elissia 非常渴望有一雙。」"'),
        ('"\\"I provide Fawn with adventuring supplies... Though I regret that my stock is not great at the moment. These storms have made the supply wagons from the other cities rare indeed.\\" *\\"What dost thou wish to purchase?\\""', '"「我為幼鹿城( Fawn )提供冒險補給品……雖然我很遺憾目前的庫存不多。這些風暴讓來自其他城市的補給車變得非常罕見。」 *「你想要買什麼？」"'),
        ('"\\"The storms... oh, yes. They\'re very interesting to watch. Though my daughter will not allow me to go outside where I can see better.\\" *\\"So many pretty colors, and such unusual results...\\""', '"「風暴……哦，是的。觀看它們非常有趣。雖然我女兒不允許我去外面，那裡視野更好。」 *「那麼多漂亮的顏色，以及如此不尋常的結果……」"'),
        ('"\\"Father, thou WILT stay indoors when those storms come through town!\\""', '"「父親，當這些風暴穿過城鎮時，你必須待在室內！」"'),
        ('"\\"Ah... I suppose I must if thou sayest so, my dear.\\""', '"「啊……既然妳這麼說，我想我必須這麼做，親愛的。」"'),
        ('"\\"Of course. Um, what was it we were discussing...?\\""', '"「當然。嗯，我們剛才在討論什麼……？」"'),
        ('"\\"Thou hast met my daughter? I had forgotten, I\'m sorry. Alyssand is very pretty, but she worries too much about me.\\" *\\"She doth not believe that I\'d be all right without her.\\""', '"「你見過我女兒了？我忘了，很抱歉。Alyssand 很漂亮，但她太擔心我了。」 *「她不相信沒有她我也會沒事。」"'),
        ('"\\"Thou dost need me, father. Thy business is much too complex for thee to run by thyself!\\""', '"「你需要我，父親。你的生意太複雜了，你一個人經營不來！」"'),
        ('"\\"Ah, er... I can do fine without thee, my dear.\\""', '"「啊，呃……沒有妳我也能做得很好，親愛的。」"'),
        ('"\\"Hmmm... what were we discussing, "', '"「嗯……我們剛才在討論什麼， "'),
        ('"?\\""', '"？」"'),
        ('"\\"Alyssand is around somewhere... Or at least she was. She never leaves me alone for long.\\" *\\"She hovers over me quite a bit since Keth disappeared... Alyssand\'s my daughter. Didst thou know?\\""', '"「Alyssand 就在附近……或者至少她剛才在。她從來不會讓我一個人待太久。」 *「自從 Keth 失蹤後，她就一直在這附近徘徊……Alyssand 是我女兒。你知道嗎？」"'),
        ('"\\"Father, that is my business!\\""', '"「父親，那是我的私事！」"'),
        ('"\\"Er... I am sorry, daughter.\\""', '"「呃……我很抱歉，女兒。」"'),
        ('"\\"Hast thou seen Keth? If so, thou shouldst tell him that Alyssand still doth have the engagement ring... Or did have it... I think she said something about losing it.\\" *\\"\'Tis not right to say that thou wilt marry someone and then not return...\\""', '"「你見過 Keth 嗎？如果見過，你應該告訴他 Alyssand 還留著那枚訂婚戒指……或者說曾經留著……我想她說過弄丟了。」 *「說你要和某人結婚，然後卻不回來，這是不對的……」"'),
        ('"\\"Keth was passing proud of that ring. He ordered it specially from someone in Moonshade...\\" \\"Mine Elissia was from Moonshade. Oh, my poor Elissia... She\'s gone. Gone.\\""', '"「Keth 對那枚戒指非常自豪。他特別從月影城( Moonshade )的人那裡訂製的……」 「我的 Elissia 也是來自月影城( Moonshade )。哦，我可憐的 Elissia……她走了。走了。」"'),
        ('"@Art thou daft, old man!@"', '"@你瘋了嗎，老頭！@"'),
        ('"\\"Elissia... Dear, sweet Elissia...\\""', '"「Elissia……親愛的，甜美的 Elissia……」"'),
        ('"@Be gentle with him. I fear he\'s a bit confused.@"', '"@對他溫柔點。恐怕他有點糊塗了。@"'),
        ('"\\"I\'m sorry... very sorry, "', '"「我很抱歉……非常抱歉， "'),
        ('". I still mourn the loss of my wife.\\""', '"。我仍在哀悼我妻子的離世。」"'),
        ('"\\"Now, thou didst ask about Alyssand\'s ring... I would call her and ask her to show it to thee, but Alyssand lost her ring not long ago.\\""', '"「現在，你問起了 Alyssand 的戒指……我很想叫她拿給你看，但 Alyssand 不久前弄丟了她的戒指。」"'),
        ('"\\"I cannot know if the ring thou didst find is my daughter\'s unless I see it. Perhaps if thou dost bring it to me I can ascertain whether thou shouldst speak with Alyssand.\\""', '"「除非我看到它，否則我無法確定你找到的戒指是不是我女兒的。也許如果你把它帶來給我，我就可以確定你是否應該跟 Alyssand 談談。」"'),
        ('"\\"Why, it certainly doth look like it... Alyssand will be so happy!\\""', '"「為什麼，這看起來確實很像……Alyssand 會很高興的！」"'),
        ('"\\"I would reward thee for returning it to her, "', '"「我會因為你把它還給她而獎賞你， "'),
        ('", but a storm stripped my cash box of all my funds the other day.\\""', '"，但前幾天一場風暴把我的錢箱裡所有的錢都捲走了。」"'),
        ('"\\"I went to open my shop the next morning and there was a bundle of food in place of the Filari Alyssand had put there the night before.\\""', '"「第二天早上我去開店時，發現 Alyssand 前一天晚上放在那裡的菲拉利幣( Filari )不見了，取而代之的是一包食物。」"'),
        ('"@That is what happened to our food!@"', '"@這就是我們食物的下落！@"'),
        ('"\\"I had forgotten that thou wert from Monitor, "', '"「我忘了你是來自蒙利多城( Monitor )了， "'),
        ('"\\"Thou must be a stranger...\\""', '"「你一定是個陌生人……」"'),
        ('"\\"Filari are Fawn\'s currency... A small silver disk with a colored gem in the center.\\""', '"「菲拉利幣( Filari )是幼鹿城( Fawn )的貨幣……一種中間鑲有彩色寶石的銀色小圓盤。」"'),
        ('"\\"Yes... yes. Those are Filari.\\""', '"「是的……是的。那些就是菲拉利幣( Filari )。」"'),
        ('"\\"That is as much as the storm took from me...\\""', '"「風暴從我這裡拿走的就是這麼多……」"'),
        ('"@These must be his coins then, Avatar!@"', '"@那麼這些一定是他的硬幣了，聖者！@"'),
        ('"\\"I would accept thy money if thou dost wish to purchase something.\\""', '"「如果你想買些什麼，我願意收下你的錢。」"'),
        ('"\\"If thou wouldst come to my shop when I am open I wouldst gladly sell thee something, "', '"「如果你在我開店時來到我的店裡，我很樂意賣給你一些東西， "'),
        ('"...\\""', '"……」"'),
        ('"\\"Of course Keth hath not returned! He would have come to see Alyssand the moment he set foot on shore.\\" *\\"No one hath seen him or his crewmates since one of those storms.\\""', '"「Keth 當然沒回來！他一踏上岸就會來看 Alyssand 的。」 *「自從其中一場風暴之後，就沒人見過他和他的船員了。」"'),
        ('"\\"Oh, yes! Thou shouldst watch one of these storms some time. The lightning is all different colors...\\" *\\"Of course, if thou strayest too far out to watch, thou mayest not enjoy it too much.\\""', '"「哦，是的！你應該找個時間看看這些風暴。閃電的顏色都不一樣……」 *「當然，如果你為了觀看而走得太遠，你可能就不會那麼享受了。」"'),
        ('"\\"Results? Results of what? What were we talking about...\\" *\\"Now I remember! The storms! There are two reasons these storms are fun to watch.\\""', '"「結果？什麼結果？我們剛才在說什麼……」 *「現在我想起來了！風暴！觀看這些風暴很有趣有兩個原因。」"'),
        ('"\\"Sometimes \'tis FLASH!, and something thou wert standing across from is gone.\\""', '"「有時會『轟！』的一聲，然後你對面的東西就不見了。」"'),
        ('"\\"But sometimes \'tis FLASH!, and something thou wert watching is a big, orange pumpkin.\\""', '"「但有時『轟！』的一聲，你正在看著的東西就變成了一個巨大的橙色南瓜。」"'),
        ('"\\"I like the last one best... \'Tis fun to guess what will be there after the flash.\\""', '"「我最喜歡最後一種情況……猜測閃光之後會出現什麼很有趣。」"'),
        ('"@Sounds like he doth have a sense of humor like thine, Iolo!@"', '"@聽起來他的幽默感跟你很像，伊歐洛( Iolo )！@"'),
        ('"@This man is quite jovial!@"', '"@這個人真愉快！@"'),
        ('"\\"\'Tis such an incredible sight. Ho ho hee!\\""', '"「這真是個不可思議的景象。呵呵嘻！」"'),
        ('"@\'Tis not very funny if what was hit was a person!@"', '"@如果被擊中的是個人，那可就不好笑了！@"'),
        ('"\\"Why wouldst thou want to talk about them? The storms are much more fun...\\""', '"「你為什麼想談論他們？風暴有趣多了……」"'),
        ('"@We do not have time for this!@"', '"@我們沒時間搞這些！@"'),
        ('"\\"Oh, all right! Don\'t be testy!\\""', '"「哦，好吧！別生氣！」"'),
        ('"\\"Thou dost not need to scowl so. Everyone is so serious these days! \'Tis not healthy, thou knowest.\\" *\\"The Goblins are large, mean and hateful. They prefer to eat humans and they make it unsafe to travel. But I never travel since they took away my son, Freli...\\""', '"「你不需要皺眉頭。最近每個人都很嚴肅！你知道的，這不健康。」 *「哥布林體型龐大，卑鄙又可惡。他們喜歡吃人，並使旅行變得不安全。但自從他們帶走我兒子 Freli 之後，我就再也沒有旅行過了……」"'),
        ('"\\"Nothing is safe... Not even life. I lost my dear Elissia after childbirth...\\""', '"「沒有什麼是安全的……甚至是生命。我在 Elissia 生產後失去了我親愛的她……」"'),
        ('("Delin, we would be most grateful.@" & "@I fear that my <Check> becoming a bit impatient.@")', '("Delin，我們會非常感激的。@" & "@我怕我的<Check>變得有點不耐煩了。@")'),
        ('"@If thou couldst return to the subject at hand, "', '"@如果你能回到手邊的話題，"'),
        ('"\\"I wandered off again, didn\'t I? What was I saying...?\\" *\\"The Goblins have killed our healer, and now we have to make do with a horticulturist. Imagine that! And, of course, the Goblins have attacked the Fawn Tower.\\""', '"「我又離題了，是不是？我剛才說到哪了……？」 *「哥布林殺了我們的治療師，現在我們只能湊合著用一個園藝師。想像一下！當然，哥布林也攻擊了幼鹿塔( Fawn Tower )。」"'),
        ('"\\"Oh, she was a true beauty, I tell thee! Soft golden hair and the brightest eyes that thou hast seen.\\" *\\"Though she came from Moonshade, no one had cause to fear her. She had not a drop of magic...\\""', '"「哦，我告訴你，她可是個真正的美人！柔軟的金髮和你見過最明亮的眼睛。」 *「雖然她來自月影城( Moonshade )，但沒有人需要害怕她。她一點魔法也不會……」"'),
        ('"\\"Other than her smile.\\""', '"「除了她的笑容。」"'),
        ('"\\"Our friend Iolo shares thy grief, milord. His wife is lost somewhere in these lands.\\""', '"「我們朋友伊歐洛( Iolo )也與你同悲，大人。他的妻子在這些土地上的某個地方失蹤了。」"'),
        ('"\\"For thy sake, I hope that she doth live, stranger Iolo.\\""', '"「為了你，我希望她還活著，陌生人伊歐洛( Iolo )。」"'),
        ('"\\"If Gwenno were lost from me forever, perhaps I too would be a little confused.\\""', '"「如果 Gwenno 永遠離我而去，也許我也會有點糊塗的。」"'),
        ('"\\"Condolences to thee, Delin, and apologies if we have been unfeeling.\\""', '"「向你致哀，Delin，如果我們顯得冷酷無情，也向你道歉。」"'),
        ('"\\"They say that I shall feel better soon...\\""', '"「他們說我很快就會好點的……」"'),
        ('"\\"But I don\'t believe it.\\""', '"「但我不相信。」"'),
        ('"\\"His name was, ah... Seth, I believe. Good healer, but he had a nasty temper.\\" *\\"I am certain that the Goblins found him a bitter meal. Ha!\\""', '"「他的名字是，啊……Seth，我相信。好治療師，但他脾氣很差。」 *「我敢肯定哥布林覺得他很難吃。哈！」"'),
        ('"\\"Seth? Oh, the healer! Didst thou know him, too?\\" *\\"Always insisted on going herb gathering alone... \'Tis what finally killed him. Wouldn\'t take any guards along with him, even after the Goblin attacks increased.\\""', '"「Seth？哦，那個治療師！你也認識他嗎？」 *「總是堅持獨自去採藥……這就是最後害死他的原因。即使在哥布林攻擊增加後，也不願意帶任何守衛同行。」"'),
        ('"\\"Did I say something about a horticulturist? I thought we were talking about healers...\\" *\\"When Seth was killed, Delphynia took his place. We could not obtain a replacement from anywhere because of the storms.\\""', '"「我有說到園藝師嗎？我以為我們在談論治療師……」 *「當 Seth 被殺時，黛爾菲妮亞( Delphynia )接替了他的位置。因為風暴的關係，我們無法從任何地方找到替代人選。」"'),
        ('"\\"Delphynia is a fine horticulturist, to be sure. But she hath had little or no training as a healer.\\""', '"「不可否認，黛爾菲妮亞( Delphynia )是個出色的園藝師。但她幾乎沒有受過治療師的訓練。」"'),
        ('"\\"And it doth not seem right having a woman as a healer. Women should concern themselves with the delights of life, not the sorrows.\\""', '"「而且讓女人當治療師似乎不太對。女人應該關心生活中的快樂，而不是悲傷。」"'),
        ('"\\"But then thou knowest all about Goblin treachery, being a Pikeman and all.\\""', '"「但身為長槍兵( Pikeman )，你肯定對哥布林的背叛瞭若指掌。」"'),
        ('"\\"Everyone is so relieved that thy fine Pikemen companions have retaken the Tower from Pomdirgun. But they do not understand that it is only a matter of time before we die... Admittedly though, I will grant that most any death would be better than becoming a Goblin\'s supper.\\""', '"「每個人都很高興你那些優秀的長槍兵( Pikeman )同伴從 Pomdirgun 手中奪回了塔。但他們不明白，我們死只是遲早的事……雖然我承認，幾乎任何一種死法都比成為哥布林的晚餐好。」"'),
        ('"\\"Everyone is so worried, now that Pomdirgun hath taken the Tower from thy Pikemen companions. But they do not understand that it is only a matter of time before we die... But I intend to try my luck with the storms, rather than becoming a Goblin\'s supper.\\""', '"「現在 Pomdirgun 從你那些長槍兵( Pikeman )同伴手中奪走了塔，每個人都很擔心。但他們不明白，我們死只是遲早的事……但我打算去碰碰風暴的運氣，也不要成為哥布林的晚餐。」"'),
        ('"\\"Everyone is so relieved that the Tower hath been retaken from Pomdirgun. But they do not understand that it is only a matter of time before we die... Admittedly though, I will grant that most any death would be better than becoming a Goblin\'s supper.\\""', '"「每個人都很高興塔已經從 Pomdirgun 手中奪回了。但他們不明白，我們死只是遲早的事……雖然我承認，幾乎任何一種死法都比成為哥布林的晚餐好。」"'),
        ('"\\"Everyone is so worried, now that Pomdirgun holds the Tower.\\" ~\\"But they do not understand that it is only a matter of time before we die... But I intend to try my luck with the storms, rather than becoming a Goblin\'s supper.\\""', '"「現在 Pomdirgun 佔領了塔，每個人都很擔心。」 ~「但他們不明白，我們死只是遲早的事……但我打算去碰碰風暴的運氣，也不要成為哥布林的晚餐。」"'),
        ('"\\"I am certain that Pomdirgun would be very disappointed to learn that thou dost not know of him. He hath gone to great lengths to be sure that we in Fawn know the name of the Goblin leader that will bring us to our knees...\\""', '"「我敢肯定 Pomdirgun 如果知道你不認識他會非常失望的。他費盡心機確保我們幼鹿城( Fawn )的人都知道這個即將讓我們屈服的哥布林領袖的名字……」"'),
        ('"\\"...Or his stewpot.\\""', '"「……或者成為他燉鍋裡的食物。」"'),
        ('"\\"The Magister comes like a thief in the night, to test the children of the land for magic talent. If a Mage Child is discovered, the Magister steals the child.\\""', '"「大師( Magister )像夜間的盜賊一樣，來測試這片土地上的孩子們是否有魔法天賦。如果發現了魔法之子，大師就會偷走那個孩子。」"'),
        ('"\\"Just as he stole my little Freli...\\""', '"「就像他偷走了我的小 Freli 一樣……」"'),
        ('"\\"Thou dost not work for the Magister, dost thou?\\""', '"「你不是為大師( Magister )工作的吧？」"'),
        ('"\\"Thou hast no cause to spy on me! I have not seen or heard from my son since he left here! I am not responsible for anything he may have done!\\" *\\"Tell thine employer that he took Freli, let him be responsible!\\""', '"「你沒有理由監視我！自從我兒子離開這裡後，我就再也沒見過他也沒聽過他的消息！我對他可能做的任何事都不負責！」 *「告訴你的雇主，是他帶走 Freli 的，讓他去負責！」"'),
        ('"@Spy not on me!@"', '"@別監視我！@"'),
        ('"\\"Good! Because the Magister hath no call to spy on me.\\""', '"「很好！因為大師( Magister )沒有理由監視我。」"'),
        ('"\\"I have had no contact with Freli since he was taken away. No mortal can win in a struggle against wizards...\\""', '"「自從 Freli 被帶走後，我就沒有和他聯絡過。沒有凡人能在與巫師的鬥爭中獲勝……」"'),
        ('"\\"Moonshade is where my wife was from... She was the most patient of women.\\" *\\"Moonshade is ruled by Mages. To them, if thou art not a Mage, thou art nothing. The Mages shed no tears when mine Elissia left the town. She was nothing in their eyes... But everything in mine.\\""', '"「月影城( Moonshade )是我妻子的故鄉……她是最有耐心的女人。」 *「月影城( Moonshade )由法師統治。對他們來說，如果你不是法師，你什麼都不是。當我的 Elissia 離開小鎮時，法師們沒有流一滴眼淚。在他們眼中她什麼都不是……但在我眼中卻是全部。」"'),
        ('"\\"Bats? What bats?\\""', '"「蝙蝠？什麼蝙蝠？」"'),
        ('"@Not bats! B-A-T-L-I-N!@"', '"@不是蝙蝠！巴-特-林( B-A-T-L-I-N )！@"'),
        ('"\\"No need to shout. I\'m not deaf.\\""', '"「不需要大吼。我沒聾。」"'),
        ('"\\"Batlin... ah, I remember he came here asking about some sort of rock sculpture or something. Black rock...\\""', '"「巴特林( Batlin )……啊，我記得他來過這裡詢問某種岩石雕塑還是什麼的。黑色的岩石……」"'),
        ('"\\"I told him I am a simple merchant. I do not carry such luxuries. I directed him to Monitor. There is a sculptor there.\\""', '"「我告訴他我只是一個單純的商人。我沒有賣這種奢侈品。我指引他去了蒙利多城( Monitor )。那裡有一位雕塑家。」"'),
        ('"\\"And people accuse me of being forgetful! Thou art a Knight, and doth ask me about Monitor?\\""', '"「人們還說我健忘！你是個騎士，還問我關於蒙利多城( Monitor )的事？」"'),
        ('"\\"Monitor is south of us, "', '"「蒙利多城( Monitor )在我們的南邊， "'),
        ('", on the coast. Their soldiers, the Pikemen, act as guards for the roads, and as highwaymen for Monitor\'s coffers...\\""', '"，在海岸上。他們的士兵，長槍兵( Pikeman )，充當道路的守衛，也充當蒙利多城( Monitor )金庫的攔路強盜……」"'),
        ('"\\"Yes, highwaymen! They charge each traveller and merchant who would make use of the road they guard!\\" *\\"An exorbitant amount doth go to Monitor every year, I\'m certain. And then we must feed them in their Tower, and offer them our goods at a discount!\\""', '"「是的，攔路強盜！他們向每個使用他們守衛道路的旅行者和商人收費！」 *「我敢肯定，每年有一大筆錢流向蒙利多城( Monitor )。然後我們還必須在他們的塔裡餵飽他們，並以折扣價提供我們的商品！」"'),
        ('"\\"A letter from Freli! Oh, what joy!\\""', '"「一封來自 Freli 的信！哦，太高興了！」"'),
        ('"\\"Let me have it! Alyssand must hear of this.\\""', '"「把它給我！Alyssand 一定要聽聽這個。」"'),
        ('"\\"I am here, father! Tell me how Freli fares. Hath he become a Mage?\\""', '"「我在這裡，父親！告訴我 Freli 過得怎麼樣。他成為法師了嗎？」"'),
        ('"\\"A moment, a moment... It will take me a moment. His writing is terrible!\\""', '"「等一下，等一下……我要花點時間。他的字寫得太糟糕了！」"'),
        ('"\\"Oh, for this piece of good work, "', '"「哦，為了這件好事， "'),
        ('", thou must be rewarded!\\""', '"，你必須得到獎賞！」"'),
        ('"\\"Let me see... ah, yes! How wouldst thou like a discount on anything within the store? Yes, yes... half my normal price -- but just this once!\\""', '"「讓我想想……啊，是的！店裡任何東西都給你打折怎麼樣？是的，是的……我平時價格的一半——但就這一次！」"'),
        ('"\\"Thou art having fun with me, stranger! I see no letter.\\""', '"「你是在拿我尋開心吧，陌生人！我沒看到什麼信件。」"'),
        ('"@Out with ye!@"', '"@給我出去！@"'),
        ('"@Thanks for thine help!@"', '"@謝謝你的幫助！@"'),
        ('"@Come back any time!@"', '"@隨時歡迎再來！@"'),
    ]

    for old, new in replacements:
        content = content.replace(old, new)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

translate_file('d:/git/Ultima7-SI-zh-TW/SerpentIsle/zh_scripts/014/042F_zh.es')
