#game "serpentisle"
void Func0638 object#(0x638) ()
{
	var var0000;

	if (!(event != 0x0001)) goto labelFunc0638_0009;
	return;
labelFunc0638_0009:
	UI_play_sound_effect2(0x005E, item);
	UI_book_mode(item);
	var0000 = UI_get_item_quality(item);
	UI_play_sound_effect2(0x005E, item);
	UI_book_mode(item);
	if (!(var0000 == 0x0078)) goto labelFunc0638_00D1;
	message("SHIP'S LOGBOOK*");
	say();
	message("Day 24:   Still looking for the miser's treasure.");
	say();
	message("\t\t\t   Fair wind and weather all day. The men are as excited as ever.");
	say();
	message("\t\t\t   Plundered a passing ship, appropriated some gold and wine.");
	say();
	message("\t\t\t   Lost one man in the fight.");
	say();
	message("Day 31:   Very stormy weather and worse at night.");
	say();
	message("\t\t\t   No encounter.");
	say();
	message("Day 32:   Uneventful except for repairs from last night's storm.");
	say();
	message("Day 40:\tThis hideout is not easy to find. The men are becoming nervous.");
	say();
	message("Day 41:\tIce filling the horizon! Temperature hath dropped.");
	say();
	message("\t\t\t\tWe are freezing. The men complain they have never seen");
	say();
	message("\t\t\t\tsuch weather this time of the year.");
	say();
	message("\t\t\t\tBurning more and more oil to stay warm. Our provisions are");
	say();
	message("\t\t\t\tdiminishing rapidly.");
	say();
	message("Day 45:   Strange how ice magnifies all.");
	say();
	message("\t\t\t\tLeaden sky is upon us. On the word of a pirate, we will");
	say();
	message("\t\t\t\tpierce through this as a sword through soft bellies!");
	say();
	message("\t\t\t\tA day of dead calm.");
	say();
	message("Day 54:\tWas forced to hang a brace of men who stole some food from the cook.");
	say();
	message("\t\t\t\tThe weather combined with our disappointing search for the");
	say();
	message("\t\t\t\tmiser's base hath created an unbearable atmosphere.");
	say();
	message("\t\t\t\tIce is surrounding us and it feels as though we are imprisoned in");
	say();
	message("\t\t\t\tthis place.");
	say();
	message("Day 55:\tWe had a storm last night. Two men were found frozen on");
	say();
	message("\t\t\t\tthe quarter-deck. One man missing. He most likely went overboard due");
	say();
	message("\t\t\t\tto the dense and damp fog, in that cold, inky black night.");
	say();
	message("\t\t\t\tThis treasure hunt is costing us too many men, and might");
	say();
	message("\t\t\t\tcost us even more...");
	say();
	message("Day 56:\tWe are wedged in by an icefloe. Food is running low.");
	say();
	message("\t\t\t\tFrozen land all around us, the ship is trapped.");
	say();
	message("\t\t\t\tAnd so are we.");
	say();
	message("Day 57\t\tMuch arguing about rations.");
	say();
	message("\t\t\t\tWe are down to our last portion. We are but a few survivors,");
	say();
	message("\t\t\t\tbundled in our rags. The terror of the seas, HA!");
	say();
	message("\t\t\t\tWe would not scare a mouse these days.");
	say();
	message("Day 58:   Finishing each other is what we have been doing for");
	say();
	message("\t\t\t\tthe last twenty-four hours. Such a waste! 'Tis only the");
	say();
	message(" \t\t\ttwo of us now and a portion of food, a single portion of food.");
	say();
	message("\t\t\t\tYet I shall not give in!");
	say();
labelFunc0638_00D1:
	if (!(var0000 == 0x0079)) goto labelFunc0638_019B;
	message("JOURNAL~~*");
	say();
	message("Day 17 -- Everyone is overjoyed that we have actually ");
	say();
	message("\t\t\t\treached the northern marches, including myself.");
	say();
	message("\t\t\t\tI look forward to setting camp and finding treasure!*");
	say();
	message("Day 22 -- We were forced to kill a pair of wolves near the encampment.");
	say();
	message("Day 28 -- The men are upset that no gold hath been found...");
	say();
	message("\t\t\t\tHowever, I remain confident of our venture.*");
	say();
	message("Day 40 -- Finding more wolves than gold.");
	say();
	message("Day 41 -- Gold. At last!");
	say();
	message("Day 45 -- Women and children are finding gold nuggets.");
	say();
	message("\t\t\t\tHow exciting! This is fabulous!");
	say();
	message("\t\t\t\t'Tis finally paying.*");
	say();
	message("Day 69 -- More have been eaten alive.");
	say();
	message("\t\t\t\tWolves. More wolves.");
	say();
	message("\t\t\t\tMen behaving like wolves. Worse than wolves.");
	say();
	message("\t\t\t\tThey are after our gold.");
	say();
	message("\t\t\t\tFor them, life is suddenly worthless.");
	say();
	message("\t\t\t\tHow could they value a nugget more than its");
	say();
	message("\t\t\t\ttrue worth?*");
	say();
	message("Day 108 -- No one can be trusted.");
	say();
	message("\t\t\t\tWho will be the next target?");
	say();
	message("\t\t\t\tHopefully, I will survive and my gold will not");
	say();
	message("\t\t\t\tbe stolen.*");
	say();
	message("Day 121 -- Something horrible happened to Hamlin.");
	say();
	message("\t\t\t\tHe was found with his throat slit and, ");
	say();
	message("\t\t\t\tof course, his gold was missing.");
	say();
	message("\t\t\t\tThis worthless gold that he hath");
	say();
	message("\t\t\t\tpainstakingly gathered killed him.");
	say();
	message("\t\t\t\tSo, this is what it hath come to...");
	say();
	message("\t\t\t\tGoldthirsty and bloodthirsty bastards.*");
	say();
	message("Day 127 -- I have finally found a vein of gold, from whence");
	say();
	message("\t\t\t\tI retrieved a small quantity with");
	say();
	message("\t\t\t\tmy pick.*");
	say();
	message("Day 148-149 --  I lay awake on my bedroll all night ");
	say();
	message("\t\t\t\tuntil dawn, cannot seem to be able to sleep.");
	say();
	message("\t\t\t\tToo many angry thoughts disturbing my mind.");
	say();
	message("\t\t\t\tAt daybreak, I rose in a state of exhaustion.*");
	say();
	message("Day 167 -- More men are fighting amongst themselves.");
	say();
	message("\t\t\t\tI am so weary.");
	say();
	message("\t\t\t\tIs this what I wanted?");
	say();
	message("\t\t\t\tThe encampment is split into factions.");
	say();
	message("\t\t\t\tNow, I will cease writing and rest by the");
	say();
	message("\t\t\t   fire, gathering much needed strength for");
	say();
	message("\t\t\t\ttomorrow.*");
	say();
	message("Day 183 -- Draygan betrayed us. Who would have thought it?");
	say();
	message("\t\t\t\t I think bitterly of his treachery.");
	say();
	message("\t\t\t\t The ship is burnt. We are doomed.");
	say();
	message("\t\t\t\t The howling is getting closer...");
	say();
labelFunc0638_019B:
	if (!(var0000 == 0x007A)) goto labelFunc0638_01B1;
	message("HAZARD'S LEDGER");
	say();
	message("~~PELTS~Sales by customer~Expressed in monetari*");
	say();
	message("...Summer~~Glendor, 3 pelts - 90~~Miri, 1 pelt - 50~~Tranch, 6 pelts - 180 ~~Falco, 3 pelts - 90*Autumn~~Cellia of Monitor, 4 pelts - 88~~Voldin of Fawn, 2 pelts - 90~~ *Early Winter~~Tornaldo of Moonshade, 3 pelts - 1035~~Yelinda of Fawn, 4 pelts - 138~~Jorvin of Fawn, 1 pelt - 34 *Hard freeze~~Marsten of Monitor, 4 pelts - 88~~Brendann of Monitor, 2 pelts - 69~~Fedabiblio of Moonshade, 1 pelt - 34 *Late Winter~~Cellia of Monitor, 2 pelts - 63~~Torrissio of Moonshade, 4 pelts - 140*Early Spring~~Cellia of Monitor, 1 pelt - 35 *Late Spring~~Karl of Monitor, 1 pelt - 25~~Garth of Fawn, 2 pelts - 79~~Marnok, 1 pelt - 35");
	say();
labelFunc0638_01B1:
	if (!(var0000 == 0x007B)) goto labelFunc0638_020B;
	message("~~ ~~ ~~BRIGGIO'S BOOK OF ASTONISHING THINGS");
	say();
	message("~~A compiled volume of items of interest both magical and mundane~~by Briggio of Moonshade*");
	say();
	message("     In this volume, compiled for easy reference, are some of the many fascinating constructions I have found during my researches. These items range from interesting uses for mundane items to fascinating miscarriages of magic.*");
	say();
	message("Wands: A trio of terrible weaponry.~");
	say();
	message("     The three identified varieties of magical wand all seem to have been made for the express purpose of changing the combat-weak spellcaster into a battle-ready automaton. And, for those with the ability to keep them from losing their potency (no small feat of magic, mind thee, but simple for anyone capable of crafting the wand in the first place), they are perhaps the most formidable weapons of their size.~~");
	say();
	message("Fire Wand: This wand releases a bolt of flaming death. According to all known texts on the subject, the carnage was called \"amazing.\"~");
	say();
	message("Lightning Wand: The effect of a bolt of lightning as it bursts forth from the wand is as devastating as its counterpart, the fire wand. However, according to one of its proponents, \"the corpses look and smell much less offensive.\"~");
	say();
	message("Magician's Wand: While only slightly more lethal than the typical bow, this wand is rendered quite effective due to two interesting facets: Its damage is of a most magical nature and more than powerful against monsters with a predilection for challenging mages, and, it NEVER ceases to function. If thou art interested in power and duration, this is the wand for thee.*");
	say();
	message("FireDoom Staff: Lethality itself.~");
	say();
	message("This staff, which hurls exploding fireballs that actually seek out a target, is perhaps the most lethal of all magical weapons created in the era of human-gargoyle cooperation. But, as with most of the more powerful magic weapons, its limited life means it may fail thee at the worst of times.*");
	say();
	message("Glass Swords : A historical legacy of death.~");
	say();
	message("These single-use swords will almost always kill any creature in a single blow, but they are seldom useful for a second opponent.*");
	say();
	message("Other Miscellaneous Magical Weaponry.~");
	say();
	message("As a general case, any person with a modicum of magical talent can identify magical weapons, armour and other apparatus by their pulsating glow. Often, however, the color indicates even more about the item than merely the existence of the enchantment. For example, a green field often denotes a poisoning weapon.~~");
	say();
	message("Burst Arrows: An arrow of myriad targets.~");
	say();
	message("The arrow functions as a normal arrow, but upon impact, explodes into a thousand flying shards of death.~~");
	say();
	message("Venom Dagger : The assassin's tool.~");
	say();
	message("This shimmering green dagger is actually the enchanted tooth of a poisonous sea serpent, joined to the hilt of a normal dagger. Its envenomed blade injects a slow poison into its victim, but it frequently breaks. It is the perfect assassination weapon (see Alagner's History, Assassination of Baron Johann IV (page 54)).*");
	say();
	message("Stone Harpy: Unnatural beast.~");
	say();
	message("The stone harpy is the creation of the twisted mind of the magus. It is reputed to be magically triggered by the close approach of any creature.");
	say();
labelFunc0638_020B:
	if (!(var0000 == 0x007C)) goto labelFunc0638_02A9;
	message("~~ ~~ ~~DRINKING SONGS DUPRE TAUGHT ME~~ ~~Volume One*");
	say();
	message("MAIDS IN TRADES");
	say();
	message(" ");
	say();
	message("Come all of ye trades and ye tradesmen,");
	say();
	message("and let ye be wise that are fools.");
	say();
	message("But remember each day that your trade would decay");
	say();
	message("if a maid did not look to your tools.");
	say();
	message(" ");
	say();
	message("The blacksmith, the smokey old blacksmith,");
	say();
	message("'tis known as a jolly old fellow.");
	say();
	message("But his iron would burn old,");
	say();
	message("and his fire would grow cold,");
	say();
	message("If a maid did not blow up the bellows.");
	say();
	message("And then there's the candlestick maker,");
	say();
	message("he works up the tallow so quick.");
	say();
	message("But his craft would be marred,");
	say();
	message("and the works not get hard,");
	say();
	message("If a maid did not hold up the wick.");
	say();
	message(" ");
	say();
	message("The ploughman, the jolly old ploughman,");
	say();
	message("he follows the plow in the silt.");
	say();
	message("But 'tis ne'er a clod turned,");
	say();
	message("if a maid had not learned him,");
	say();
	message("To drive the blade up to the hilt.");
	say();
	message(" ");
	say();
	message(" ");
	say();
	message("The brewer, the jolly old brewer,");
	say();
	message("he maketh a very fine ale.");
	say();
	message("But his brew would be waste,");
	say();
	message("if there's no maid to taste,");
	say();
	message("And make sure that it doesn't grow stale.");
	say();
	message(" ");
	say();
	message("So come all ye journeymen, craftsmen,");
	say();
	message("and all that are apprenticed to trade.");
	say();
	message("For 'tis ne'er a screw");
	say();
	message("or a nut would be turned,");
	say();
	message("If it weren't for the help of a maid!");
	say();
labelFunc0638_02A9:
	if (!(var0000 == 0x007D)) goto labelFunc0638_033B;
	message("~~ ~~ ~~DRINKING SONGS DUPRE TAUGHT ME~~ ~~Volume Two*");
	say();
	message("ROLL THY LEG OVER");
	say();
	message(" ");
	say();
	message("If all the young ladies were little white rabbits,");
	say();
	message("I'd be a hare, and teach them bad habits!");
	say();
	message(" ");
	say();
	message("Refrain:");
	say();
	message("Roll thy leg over,");
	say();
	message("roll thy leg over,");
	say();
	message("Roll thy leg over");
	say();
	message("the man in the moon.");
	say();
	message(" ");
	say();
	message("If all the young ladies were bricks in a pile,");
	say();
	message("I'd be a mason and lay them in style!");
	say();
	message(" ");
	say();
	message("If all the young ladies were cocks in the hay,");
	say();
	message("I'd be a hen, and I'd have a good lay.");
	say();
	message(" ");
	say();
	message("If all the young ladies were bats in a steeple,");
	say();
	message("and I were a bat, there'd be more bats than people.");
	say();
	message(" ");
	say();
	message("If all the young ladies were bells in a tower,");
	say();
	message("and I were a clapper, I'd ring every hour!");
	say();
	message(" ");
	say();
	message("If all the young ladies were doors of stout wood,");
	say();
	message("and I were a knocker, I'd bang them up good!");
	say();
	message("If all the young ladies were stones in a mill,");
	say();
	message("and I were some grain between them, I'd spill...");
	say();
	message(" ");
	say();
	message("If all the young ladies were coconuts sweet,");
	say();
	message("I'd suck out their juices and chew on their meat.");
	say();
	message(" ");
	say();
	message("If all the young ladies were birds in their nests,");
	say();
	message("I'd be an egg and lie under their breasts.");
	say();
labelFunc0638_033B:
	if (!(var0000 == 0x007F)) goto labelFunc0638_0359;
	message("~~ ~~VETRON'S GUIDE TO WEAPONS AND ARMOUR~~ ~~Their effectiveness and value*");
	say();
	message("Here are listed, for easy comparison, various weapons and their effects upon opponents. Consider them to be rated on a scale of 1 to 100, with the lower valued weapons being less effective upon thine adversary: ~~Axe, two-handed: 10~~Blowgun: 1, causes enemy to fall asleep and be poisoned~~ Bow: 8~~Cannon: 90~~Club 2~~Crossbow: 10~~Dagger: 1~~Halberd: 10~~ Hammer: 4~~Hammer, two-handed: 9~~Knife: 2~~Mace: 5~~Main gauche: 2~~ Morningstar: 5~~Powder keg: 16~~Sling: 3~~Sword: 6~~Sword, two-handed: 11~~ Throwing axe: 4~~Torch: 3~~Whip: 4*");
	say();
	message("Armour and shields and their protection effectiveness are described here to permit the informed soldier the opportunity to select the armour best suited to his or her fighting style:~~Buckler: 1~~ Chain armour: 2~~Chain coif: 2~~Chain leggings: 2~~Crested helm: 3~~ Curved heater: 3~~Gauntlets: 2~~Gorget: 3~~Great helm: 4~~Greaves: 2~~ Kidney belt: 1~~Leather armour: 1~~Leather boots: 1~~Leather collar: 1~~ Leather gloves: 1~~Leather helm: 1~~Leather leggings: 1~~Plate armour: 4~~ Plate leggings: 3~~Scale armour: 2~~Spiked shield: 2~~Wooden shield: 2*");
	say();
	message("Here is a list of the better-known enchanted weapons:~~Magic arrow: 4~~Magic axe: 8, can be thrown~~ Magic bow: 12~~Magic sword: 7, very accurate~~Glass sword: 127, breaks*");
	say();
	message("Enchanted armour:~~Magic armour: 5,~~Magic gauntlets: 3,~~Magic gorget: 4,~~Magic helm: 5,~~Magic leggings: 4,~~Magic shield: 4*");
	say();
labelFunc0638_0359:
	if (!(var0000 == 0x008A)) goto labelFunc0638_036F;
	message("~~ ~~THE ART OF FIELD DRESSING~~ ~~by Harnna*");
	say();
	message("     Though I personally advocate the use of healing herbs and more cleanly bandaging environments, the steps told in this treatise will suffice until better healing care becomes available. Follow these steps carefully, and thou wilt have no trouble forming a reliable, if not perfect, way to prevent serious blood-loss. Remember, however, that there is no care as good as clean sheets, a sturdy bed, and proper attention!~~");
	say();
	message("     As long as one doth have shears, cloth, and a conscious mind, thou wilt have little fear of bleeding to death on the corpse-littered fields of battle. Simply cut the cloth into strips and bandages. Quickly placing the center of the bandage over the wound, wrap the strip around and around the bleeding area. As the cloth begins to soak with blood, it will combine with the natural healing aspects of the body to staunch the flow of blood and to quicken the healing process. In no time, thou wilt be ready to travel again (though I advise this travel be to the house of a competent healer!).");
	say();
labelFunc0638_036F:
	if (!(var0000 == 0x008D)) goto labelFunc0638_03A1;
	message("MY NOTEBOOK~~    Anonymous~~");
	say();
	message("     The observations enclosed herein are based on mine experiments.");
	say();
	message("Reader, for thy sake and thy thirst for knowledge, I have decided to provide thee with the following accounts.");
	say();
	message("Long ago, when I accidentally landed on this world, the primitive sentients living here erected a temple to me and my 'chariot.' But they were boring and impetuous!");
	say();
	message("Soon, the cats emerged as a more likeable group than any other creatures. Thereafter, I was to begin some experiments on them. Quite successful indeed. My liking for these cats caused me to contemplate how to widen and strengthen their intelligences.");
	say();
	message("Thereupon, I set out to modify the Power Generator. Thus began the experiments. The Generator provided the felines with a more obdurate life energy, one which was most difficult to suppress -- the cats die, yet with stubborn energy return once again to life! The side effect is that strange glow which surrounds them.");
	say();
	message("After several manipulations I was successful in increasing their lives up to nine times. Thus no one would be able to truly defeat them until their ninth life.");
	say();
	message("The source of all extra life resides in the Power Generator.");
	say();
	message("Dear reader, make of mine experiments what thou wilt.");
	say();
	gflags[0x0298] = true;
labelFunc0638_03A1:
	if (!(var0000 == 0x0096)) goto labelFunc0638_0437;
	message("~MINE EXPERIMENTS~~ by Teldrono*");
	say();
	message("~This book belongs to Teldrono~The Mage*");
	say();
	message("\tFor thee,  bright reader, I have been deep in the heart of darkness");
	say();
	message("in search of the Way. The Way to reverse or even negate the effects");
	say();
	message("of Bloodspawn hath been my quest. Stoneheart is also on my mind, thou");
	say();
	message("art right, so right... By the way, dear reader, if thou shouldst know how to obtain");
	say();
	message("some, contact me immediately. I thank thee in advance for thy kindness.");
	say();
	message("Let us begin, for I am losing track of what thou art interested in.");
	say();
	message("Thou art not afraid of dying, art thou?  Well, then I shall proceed");
	say();
	message("and tell thee what all this truly concerns.");
	say();
	message("The more I would experiment with it, the closer I would come to success.");
	say();
	message("That was mine intuition. Well, I must admit it did not work.");
	say();
	message("Bloodspawn is bound to have some side effects. I do not know which yet.*");
	say();
	message("The heart of the matter, if I may say so dear reader, is that thou art");
	say();
	message("about to take possession of a secret. Darkness may fall upon thee at the very same time. I recommend thou beest extremely careful, a fatal accident is easily triggered when manipulating those forces.");
	say();
	message("In the heart of the mountain, I found the red-orange mineral. I collected samples and, after many a transformation, I turned it into the Forbidden Reagent. Thou art certain, dearest reader,");
	say();
	message("that thou fearest death no more? I want to make it clear this is nothing like what thou hast seen before... Many a mage's life was taken away.*");
	say();
	message("\t\tHow did I turn it into a powerful magical reagent, thou askest?");
	say();
	message("Yes, indeed, how? Oh! I remember, thou hast only to crush it into a fine powder.");
	say();
	message("Then, thou dost combine the powder with fresh human blood. 'Tis just so!");
	say();
	message("\t\tThis powerful reagent, too powerful for my fellow mages who were fools enough to lose their lives, enables thee to create some spells.");
	say();
	message("It might make possible the spells to flay men's minds, or set swords into dancing death, or to decimate entire cities.");
	say();
	message("Mass death. Well, think of it, thou mayest be able to make matter disintegrate, and ");
	say();
	message("even call lightning to thy service, if I recall correctly mine experiments. These are the powers of Bloodspawn.*");
	say();
	message("\t\tDear reader, thou art now ready to experiment, or ready to lose thy life.");
	say();
	message("Remember how careful thou shouldst be when carrying it. Finding safe means to");
	say();
	message("avoid the Bloodspawn's side effects is of primary concern.");
	say();
	message("Herein, I did give thee all thou wilt ever need to know.");
	say();
	message("Thou mightest want to be prepared for fits. Experimenting with Bloodspawn");
	say();
	message("and Stoneheart will trigger numerous disorders. Many a time did I attempt");
	say();
	message("to delay the onset of the fits, all in vain, alas. The future doth not");
	say();
	message("seem to be a long shining path. I even wonder how long I will");
	say();
	message("remain sane. Thou art the reason why I wrote such a book, dear reader, it");
	say();
	message("is for thee to read and for thee to take our place once I be gone.");
	say();
	message("This powerful knowledge painfully extracted from the heart of darkness must outlive us. Thou shalt continue!");
	say();
labelFunc0638_0437:
	return;
}


