#game "serpentisle"
void Func02C1 shape#(0x2C1) ()
{
	var var0000;
	var var0001;

	if (!(event == 0x0001)) goto labelFunc02C1_06C2;
	UI_play_sound_effect2(0x005E, item);
	UI_book_mode(item);
	var0000 = UI_get_item_quality(item);
	if (!(var0000 == 0x0000)) goto labelFunc02C1_0036;
	message("~~PHILIPHUS'S WISDOM ~~  ~~by Philiphus*");
	say();
	message("~~An enlightening discourse on the enigma of programming.");
	say();
	message("~Beginning with the heretofore unresolved mysteries of global variables...");
	say();
	goto labelFunc02C1_06C2;
labelFunc02C1_0036:
	if (!(var0000 == 0x0001)) goto labelFunc02C1_0047;
	message("The path to wisdom lies before thee. If thy deeds are as virtuous as thy words, thou shalt not fail.");
	say();
	goto labelFunc02C1_06C2;
labelFunc02C1_0047:
	if (!(var0000 == 0x0002)) goto labelFunc02C1_005C;
	message("~~TEMPLE OF BALANCE*");
	say();
	message("\t Only he who hath achieved balance within this temple may be free to find greater balance on the path to the Grand Shrine.~ He who wishes to find fulfillment must use the fire of chaos and the ice of order to restore balance. ~   Only a true serpent of fire and serpent of ice will bring thee to balance.");
	say();
	goto labelFunc02C1_06C2;
labelFunc02C1_005C:
	if (!(var0000 == 0x0003)) goto labelFunc02C1_0075;
	message("~~IMPLEMENTS OF BALANCE*");
	say();
	message("  A devout follower will know the true path towards Balance. Thou shouldst know the arts necessary to achieve Balance. To those of you who have forgotten your lessons -- take heed:~~   Fire is the embodiment of the force of Chaos, ~   Ice is the embodiment of the force of Order.~ ~   The Ice Diamond and the Fire Ruby are necessary to achieve balance within the shrine.*");
	say();
	message("~   Disciple of Balance, know the true way to balance fire is with ice, and the one way to balance ice is with fire. Using thy tools of the candles of fire and the solids of ice thou mayest achieve the way to Balance and to the Shrine.");
	say();
	goto labelFunc02C1_06C2;
labelFunc02C1_0075:
	if (!(var0000 == 0x0004)) goto labelFunc02C1_008A;
	message("~~ISKERISS'S JOURNAL*");
	say();
	message("  The Great Hierophant, who feared that the followers of Chaos would attempt to gain access to the Sacred Library, ordered the Adepts of the Conjury to construct a secure means of entering the Library. The Adepts spent many long nights in contemplation, rejecting one idea after another as being too impractical. It was the suggestion of a mere apprentice, Kethiss, that was finally accepted by all of the Adepts. Our Beloved Leader, the Great Hierophant, was soon informed that there could be only one way to gain ingress into the Sacred Library. The Adepts, acting in concert, placed a charm of teleportation upon our Gate. The Great Hierophant was adamant, however, that he alone could have access to the Sacred Library. Thus, the Adepts wove the charm of teleportation so that it would only trigger when the Wand of the Serpent was used on the Gate. *  The Great Hierophant, may he live a thousand years, hath successfully entered the Sacred Library by using the Wand of the Serpent and stepping upon the Serpent Gate...");
	say();
	goto labelFunc02C1_06C2;
labelFunc02C1_008A:
	if (!(var0000 == 0x0005)) goto labelFunc02C1_0098;
	message("~  Before proceeding to the main shrine, the devout follower must reacquaint himself or herself with the six shrines of the Temple. These shrines are dedicated to the forces of: ~Discipline, Tolerance, Ethicality, Enthusiasm, Emotion, and Logic.*  One achieves enlightenment through Balance.~ ~Tolerance becomes the chain that unites the whole. ~Ethicality is a beacon to guide our actions. ~Enthusiasm is a rose that brings beauty to our rising. ~Discipline is our weapon against faltering. ~Emotion is a heart that is a reservoir of our feelings. ~Logic is calculated truths leading us from ignorance. ~Tolerance balanced with Ethicality brings us Harmony.~ ~Enthusiasm balanced with Discipline bestows Dedication upon us.~ ~Emotion blended with Logic and Logic balanced with Emotion achieve Rationality.~~ ~Only by achieving Harmony, Dedication, and Rationality can one find the path to the Grand Shrine of Balance. Balance is the key to the Shrine.");
	say();
labelFunc02C1_0098:
	if (!(var0000 == 0x0006)) goto labelFunc02C1_00BA;
	message("~~ARTIFACTS OF COMMUNION*");
	say();
	message("Before the War of Imbalance our priests did fashion three artifacts: the Web of Fate, the Moon's Eye, and a Magic Lens. Each artifact was made for a particular temple.");
	say();
	message("The Web of Fate was placed within the Temple of Tolerance. The Moon's Eye was placed within the Temple of Emotion, and the Magic Lens was placed within the Temple of Enthusiasm.");
	say();
	message("Our holy fathers used the power of these artifacts to commune with the Power of the Void -- to answer questions that the mind of mortals could never fathom.");
	say();
	message("The War of Imbalance changed everything! The artifacts no longer worked properly; the holy father's questions were left unanswered -- their hoarse voices echoed within the deserted temples.");
	say();
	message("The only power left within the holy artifacts was the ability to divine the location of the Banes of Chaos. Each artifact could spy upon a different Bane.");
	say();
labelFunc02C1_00BA:
	if (!(var0000 == 0x0059)) goto labelFunc02C1_00E0;
	message("~~ ~~ GUIDELINES OF LIFE by Shaushauna~~");
	say();
	message("1: Tolerance becomes the chain that unites the solidarity into the whole.~");
	say();
	message("2: Ethicality is a beacon to guide our actions.~");
	say();
	message("3: Enthusiasm brings beauty to our rising.~");
	say();
	message("4: Discipline is a weapon against faltering.~");
	say();
	message("5: Emotion is a heart beating strong and proud.~");
	say();
	message("6: Logic is a straight guide upon which we can rely...");
	say();
labelFunc02C1_00E0:
	if (!(var0000 == 0x004B)) goto labelFunc02C1_00F2;
	message("PENGUINS OF THE NORTH ~~Observations by Ssashartha~~");
	say();
	message("     Talking about all living creatures on our beloved Serpent Isle, we cannot forget to mention the family of the penguins. Those clumsy-looking beings are called birds even though they cannot fly. They live in the northern part of this island. Penguins are very good divers. The short wings of their strong bodies are used as a rudder. Out of the water they walk upright just as Men and the tail is an important tool to keep balance. Depending on the species, they can grow taller than 3 feet. No matter what the species, all penguins live in a sociable manner and breed in seemingly peaceful colonies. The female penguins take much pride in building the nests. Because of their size, penguin nests can easily contain more than mere eggs...");
	say();
labelFunc02C1_00F2:
	if (!(var0000 == 0x003E)) goto labelFunc02C1_0114;
	message("TENETS OF DISCIPLINE ~~Precepts by Shushuro~~");
	say();
	message("1: \"One cannot master the world around him without first mastering oneself.\"~");
	say();
	message("2: \"A task left unfinished is a task failed.\"~");
	say();
	message("3. \"The means to succeed is brought about by discipline.\"~");
	say();
	message("4. \"Discipline brings about obedience. Obedience brings about order.\"~");
	say();
	message("5. \"The mind disciplines the body.\"");
	say();
labelFunc02C1_0114:
	if (!(var0000 == 0x0058)) goto labelFunc02C1_013A;
	message("~~ ~~ TEMPLES OF ORDER~~ ~~by Shrithos*");
	say();
	message("Pilgrims, it is a great journey to visit the three Temples of Order. Do not let the obstacles sway thee from thy destination, for though the path is difficult, the rewards are many.");
	say();
	message("Seek the Fountains, for their Water is the essence of the Force which resides at that sanctuary. Imbibe the Waters, and drink of the fruit of thy quest.");
	say();
	message("The Temple of Ethicality is found near the coast, south of the Spinebreaker Mountains. It was built in such a way that those who come here may gain inspiration from the view. This is the first Temple on the Pilgrimage of Order.");
	say();
	message("Continue next to the Temple of Discipline. The western branch of the Spinebreaker Mountains is where the Temple of Discipline was carved out. Seek the great bay, then follow the eastern coast until thou dost reach the mountains. Continue east, and thou shalt be sure to find the entrance.");
	say();
	message("Lastly, the Temple of Logic lies within the Glacier Mountains, with the entrance being in the southern tip of the mountain chain. There are many passageways until one finds the Tests of Logic which lead to the sanctum.");
	say();
	message("Above all, do not mistake any Temple of Chaos for one of the sanctuaries of Order, for in this path lies Madness. Only Order is fit for study; chaos defiles all it touches.");
	say();
labelFunc02C1_013A:
	if (!(var0000 == 0x0043)) goto labelFunc02C1_0170;
	message("~~ ~~THE IMPORTANCE OF MEDITATION~~ ~~Manual by Zazanush*");
	say();
	message("    The importance of meditation becomes noticeable when people of all ages admit that they are living a better, more peaceful life since they started to seek communion with the Serpent of Order. To apply the power of meditation to one's life, young student, obey the rules and follow them as they are written in this manual. I have gathered some guidelines that are easy to understand, so that thou mayest begin with these relaxing exercises without having to investigate any further.");
	say();
	message("1: Find thyself a place where thou wilt not be disturbed by anyone or anything.~");
	say();
	message("2: Carefully spread the Mat of Meditation on the floor. Use only the prepared mats, for they are imbued with special powers to aid meditation.~");
	say();
	message("3: Kneel and close thine eyes.~");
	say();
	message("4: Concentrate on breathing very slowly and deeply.~");
	say();
	message("5: Begin repeating the mantra \"Issit.\"~");
	say();
	message("6: Do not speak.~");
	say();
	message("7: Do not let anything interrupt thee.~");
	say();
	message("8: Continue with the mantras until thou dost feel total peace of mind.~");
	say();
	message("These lessons will lead thee to a much higher level of meditation. They will prepare thee for the climax of the Test of Discipline.");
	say();
labelFunc02C1_0170:
	if (!(var0000 == 0x0052)) goto labelFunc02C1_018A;
	message("~~ ~~HISTORY OF SERPENT ISLE ~~ ~~by Harashash*");
	say();
	message("   During the First Age, the world was divided into four continents -- the LANDS OF LORD BRITISH, the LANDS OF THE FEUDAL LORDS, the LANDS OF DARK UNKNOWN, and the LANDS OF DANGER AND DESPAIR. After the evil wizard Mondain was defeated, only the Lands of Danger and Despair remained -- all other continents were destroyed.");
	say();
	message("The Lands of Danger and Despair became what we now call Serpent Isle, in honor of the Great Earth Serpent who is our guide. It was he who called to us from the Void, and in answer to our pleas, he taught us the ways of the Serpent -- the Way of Balance.");
	say();
	message("The population on Serpent Isle grew. The citizens helped each other and relied on each other. There was no crime and people were holding to their traditions. Parents taught their children about the Virtues of Order and Chaos. These traditions were passed on from generation to generation. Their devotions were presided over by the Great Hierophant. He was the only one allowed to open the Wall of Lights and enter the Void -- a magical place that connects dimensions in space and mayhap even time! Because great danger is involved in entering the Void, only the Great Hierophant is entitled to operate the Wall of Lights. Much knowledge is required for this procedure and the Great Hierophant must be in possession of the Artifacts of the Serpent.");
	say();
labelFunc02C1_018A:
	if (!(var0000 == 0x0057)) goto labelFunc02C1_01AC;
	message("~~ ~~THE TEST OF PURITY~~ ~~by Larushash*");
	say();
	message("Throughout our lives we must measure ourselves in tests of one form or another. This treatise is meant to be read by those who will be given the test of purity. Purity is important for a free soul and demands discipline, logic and ethicality from the obedient human being. Obedience demands a person who is capable of putting others first and himself last.~");
	say();
	message("Putting others first demands discipline; the ability to finish a task without being distracted.~");
	say();
	message("Putting others first demands logic that will block the emotion that may ask thee to do otherwise.~");
	say();
	message("Putting others first demands ethicality that makes one believe in abiding the rules of conduct.~");
	say();
	message("Discipline, Logic and Ethicality in their purest form and always obeyed will give one a free soul. A soul that is not enslaved by materialism, egoism and other evil characteristics. They will serve thee to the purpose of a dedicated life, a life in harmony with the ability to understand the meaning of life and the world around thee. The person that truly lives his life by these rules will be rewarded....");
	say();
labelFunc02C1_01AC:
	if (!(var0000 == 0x005B)) goto labelFunc02C1_01CA;
	message("~~THE POWER OF MAGIC~~ ~~ by Rossinoss~~");
	say();
	message("Many of us have learned with difficulty what it means when an item important to us disappears. In most cases those things disappeared forcibly -- they disappeared by theft! It became necessary to protect brave citizens and their property. People invented their own types of 'protection-devices'! Some of those were unfortunately dangerous and harmed the person they were supposed to protect. Some of them were useful and very effective. Here are some advanced techniques to protect thyself and thy property.");
	say();
	message("     To create a device that will protect thine home against fire, certain items are required. The owner will need 1 keg of moondust and 1 keg of roasted ice ants. The mixture of both must be spread around the house in a circle. Unfortunately this procedure hath not been proven to be absolutely effective yet.~");
	say();
	message("    To protect thy farm animals and pets against gruesome predators, a feed mixture out of the following ingredients is very helpful: 1 bucket of red corn, 1 bucket of fish spawn, 1 bucket of ground gargoyle horn and 1 bucket of water from the silver fountain. Feed this to the animals about once a week before sunrise.~");
	say();
	message("    The most effective way to protect doors against intruders hath been proven to be a combination puzzle for the lock.");
	say();
labelFunc02C1_01CA:
	if (!(var0000 == 0x0051)) goto labelFunc02C1_01E4;
	message("~~FUNERAL CEREMONIES~~by Javallaja~~");
	say();
	message("The darkest day of all arrives when one of our Great Hierophants lies down to close his eyes forever. The country's grief is so apparent that it seems that it may be touched. Every follower, down to the littlest child, can feel the void that unfolds with the loss of the Great Hierophant. The only way acceptable to pay our last respects is a ceremony that indicates without any doubt how important this being was to our society and how much they are missed by us.~");
	say();
	message("The body must be laid in state for three full days. After the blessings, the body will be dressed in holy clothes and decorated with holy flowers, so that the ordinary folks may greet the Great Hierophant for the last time, in a quiet manner. Loud wailing and gnashing is not tolerated. The pain must be held back until the outside of the shrine is reached. People may bring small tokens and leave them with the Hierophant to show their gratitude. A state of mourning for the period of seven days is ordered for the whole country. Every temple and every shrine will be open day and night, so people may gather at all times and share their grief.~");
	say();
	message("One last word to those people who never followed the Great Hierophant with all their heart: Rebellion, interruptions of the ceremony and all other possible disturbances will be prosecuted and punished. No crime will go unseen. Keep in mind: 'The Serpent Watches Over All!'");
	say();
labelFunc02C1_01E4:
	if (!(var0000 == 0x005D)) goto labelFunc02C1_01F6;
	message("~~ ~~ CIVIL WAR OR THE EVIL FORCES OF CHAOS ~~ by Lorick~~");
	say();
	message(" Every morning when I rise it becomes clearer and clearer to me and to many other people. The Forces of Chaos cannot be the right way of belief. What they are doing is wrong and evil. It will bring our country to a downfall. Their actions are destroying the faith of the citizens in leaders and leadership. Something must be done. There must be a way to end this Civil War. Thousands and thousands of brave followers have been victimized and sacrificed by the powers of Chaos. And thousands more are to follow if this war doth not come to an end soon. Someone must be there to help our people and protect them from the unbridled Tolerance and Anarchy of THOSE people, that were the root cause of this war. There must be a way, there must be....");
	say();
labelFunc02C1_01F6:
	if (!(var0000 == 0x0062)) goto labelFunc02C1_021C;
	message("~~ ~~Diary of Diabolical Traps~~");
	say();
	message("\tI, Seliashor, am accompanying a score of soldiers and scholars ordered to retrieve the Golden Orb.  I was chosen for my knowledge of traps; a specialty particularly suited for a journey into unknown lands controlled by a mind such as the Fiend's.~");
	say();
	message("First Level--The first trap!  A soldier, wandering into an alcove, found himself separated from his command by poison fields!  I had the good fortune to be looking his way when he triggered the trap; it is obviously of magical nature.  If this is all we will face, the ring will surely be ours.~");
	say();
	message("Second Level--The Fiend has raised the stakes! We discovered a large cavern, in which were numerous statues of harpies and decorative suits of armor.  We had immediately deduced that these were traps and would smite us if we stepped to near, but the real trap was more cleverly hidden!  Caltrops, painted to match the color of the floor, drew a great deal of blood from the soldiers as they gingerly avoided the obvious statue traps.  Clever.*");
	say();
	message("Second Level--We have discovered the next trap.  A small number of chests, clustered together, proved to be explosive if tampered with.  Amateurish--I spotted the trap before any of the foolish soldiers could tamper with it.~");
	say();
	message("Third Level--Three soldiers entered a completely barren cavern and triggered a truly fiendish trap.  When they reached the center of the room, we heard the sound of a bell.  Nervous seconds passed.  Just when we relaxed, a spell of terrifyingly destructive nature went off.  The soldiers were consumed in flames which appeared from empty air, disappeared, and reappeared in other locations.  Had they fled from the room, they would have lived.  There was a body in there, and my mind's eye can still see the light cast from our torches glinting of a golden object in its hands.  If it was the orb, it is lost, for not one of our number dares to face the flames.  I think it was naught but a gold statue or somesuch; more accurately, I hope it was.*");
	say();
	message("Third Level--we sent another soldier to his death.  He was sent into the narrow mouth of a cavern.  I knew he would not return.  When he entered the cavern, an energy field appeared in the narrow opening!  Neither I nor our wizard had Dispel Field in our spellbooks; he was left to die.  He was one of the last soldiers alive; our prospects for survival are grim.*");
	say();
labelFunc02C1_021C:
	if (!(var0000 == 0x0060)) goto labelFunc02C1_0242;
	message("~~ ~~Denizens of the Caves~~ ~~by Isstherios~~");
	say();
	message("\tDuring our inhabitance of this remote outpost we have been assaulted by creatures of such uniqueness and variety that I have taken it upon myself to create a bestiary.~");
	say();
	message("\tArachnian:  This terrifying creature has the full body, head and legs of the giant spider common to our island, with the torso, head and arms of a man growing from just behind its spider-head.  Speculation abounds as to the origin of these horrible hybrids; some claim the mad servants of Chaos created it in one of their endless foolish experiments, others say it was the work of a long-dead lunatic mage.  Regardless of how they came to be, the Arachnian is perhaps the deadliest of all foes we face here at Serpent's Fang.*");
	say();
	message("\tLiche:  This is not so much a creature as it is a being, but I consider it worthy of note here.  All of the folk I have spoken to in the keep are rather retiscent about the liche, but I have compiled the following information:  The liche was here before the keep was established.  It is undead; once alive, it entered a state of \"unliving\" which heightened its power but nullified what humanity it may have had when it was alive.  It can command undead and hurl the most devastating of spells.~");
	say();
	message("\tNaga:  A fearsome creature whose lower half is that of a giant snake and upper half is that of a human woman, the Naga is capable of delivering devastating vollies of arrows at those who dare intrude upon its lair.  The Naga's origin, like that of the Arachnian (see above) is questionable.  It is best, when a Naga is spotted, to close for battle immediately, lest their arrows bring thee down before thou hast a chance to flee.  Additionally, they have been known to use snakes as a front line while the Naga pick intruders off with arrows.*");
	say();
	message("\tShasrajah:  These menacing, scaled freaks have intimidating forms of attack; with their long, snake-like necks they thrust their heads toward their enemy, latching on with their rending teeth, then with their strong neck muscles ripping flesh off.  Though they seldom land hits, they are deceptively quick and resilient to blows.  However, they are enormously stupid, unable to even open doors.  They often attack in groups, making them more dangerous, but they are easily led into traps.  Thus have we been able to repel their regular attacks.~");
	say();
	message("\tI have considerable information on the origin of these beasts; basically, they were an attempt by the forces of Chaos to fuse viper and man.  The Lords of Discipline (those fortunate soldiers whose minds were transferred into the bodies of automatons) had brought the advantage to Order in the war, and these Shasrajah were their attempt to tip the scales in their favor.  Fortunately, the soldiers sacrificed to this wasteful end went insane in their new bodies. They escaped from the lab and began spreading their foul race all over the subterranean realms of our isle...");
	say();
labelFunc02C1_0242:
	if (!(var0000 == 0x0061)) goto labelFunc02C1_0264;
	message("~~ ~~The Lost Orbs~~ ~~Compiled by Isstherios~~");
	say();
	message("\tI have compiled this work so that, when we have the manpower to seek out the four lost orbs, all of the information we have will be available to the seeker.~");
	say();
	message("  \tThe first orb, golden in hue, was stored within the keep in a secret location until stolen by a soldier of Chaos.  He imbibed a potion of invisibility and followed behind the commander, who had gone to retrieve the orb.  When he found the room, he attacked the unwary commander and stole the orb.  However, his invisibility wore off as he was making good his escape and he was seen by a troop of guards.  The guards chased the thief until he was cornered southeast of the keep; his only escape from the guards would have been to plunge into the Fiend's Domain.  This he did, and was never seen again.  We presume it has come into the Fiend's possession and expect he will try to use it to his advantage.~");
	say();
	message("  The purple orb, reputedly housed in the Commander's bedchambers, was also purloined by a Chaosite, though this one was no soldier.  Those few who saw it will never forget it; they know not whether the thing was man, beast, or both.  The thing was bipedal and vaguely humanoid, but it had the fur, large ears, feline face, and claws of a cat.  It was being held prisoner in the keep, but an undisciplined soldier on duty relaxed on his watch and the cat-man escaped.  I know not how it found its way into the Commander's bedchambers; I assume that its escape was not well-planned and he happened upon it by chance.  However it did find the orb, the cat-man stole it and ran into the Maze.  No one has seen the creature or the orb since.*");
	say();
	message("  The red orb was not stolen, but is out of our hands all the same.  Prior to the closure of the addition to the outpost, to the southwest of the keep, SubCommander Gareth was charged with the task of transporting the orb to this area; we can assume he accomplished his mission, but Gareth never did return.  Shortly thereafter the area was surrendered to the creatures that currently reign there.  It is my presumption that the orb still rests within this catacomb.");
	say();
	message("  The blue orb is certainly the strangest tale, but its possessor is a known entity; it rests in the decayed hands of the lich Aram-Dol.  How that malevolent entity came to possess the blue orb is where the strange tale doth lie. Approximately the same time the red orb was carried to presumed safety, the blue orb was to be carried to a location only SubCommander Gareth knew.  The six automatons sent on this mission were ambushed not far from the outpost; lookouts witnessed the battle but could not send aid in time.  The attackers were assumed to be spies of Chaos, but their identities will forever be unknown. They outnumbered the automatons by fully a score; the battle was quick.  They fled away with great haste.  Later a merchant traveling to the keep from Shasavrah reported that he had seen the thieves in a small town west of the keep, but the orb was stolen from them, along with much of their supplies, in the night. The orb appeared again in the hands of authorities in Thiriastith, who siezed it from a suspected stolen goods fence.  Not knowing its import, the authorities auctioned it as a bauble to a wizard who knew what the orb was.  This wizard, who was known only as the Asp, aspired to steal the silver seed.  He came to Serpent's Fang as an adventure seeker and was told that the other orbs were stolen or lost.  He discerned their whereabouts from this information, but that which he was told was apparently not true, for he set out immediately for Aram-Dol's lair.  Foolishly, he brought the one orb he possessed with him into those foul tunnels of Aram-Dol's lair.  The dead that walk those caverns and tunnels soon forced the Asp to join them in their ever-living death.  This new soldier of Aram-Dol brought the orb to the lich, thus bringing a momentary end to its lengthy sojourn.*");
	say();
labelFunc02C1_0264:
	if (!(var0000 == 0x0063)) goto labelFunc02C1_027A;
	message("~~ ~~On Accessing the Serpent Gate~~ ~~by Shalsaraiah~~");
	say();
	message("  Though it be true that most of the Serpent Gates are centerpieces of the destinations they serve, in our fair city this is not so. To provide a measure of security, we have made our Gate inaccessible to all those who are not given permission by the Hierophant himself, for it is he who holds the keys. He doth keep on his person the Key of Fire and entrusts to an advisor (whose identity is kept secret to those outside the clergy) the Key of Ice.*");
	say();
	message("When these two keys are placed on the altar in the Great Temple, these two keys merge to form the blackrock key. It is with this key that the Hierophant opens the door to the Serpent Gate: a simple brass door on the temple's balcony. From here the traveller is teleported to a grand room, wherein he walks on graceful bridges to the Serpent Gate. I myself was once chosen to carry the Key of Ice, and I did keep it on my person even when bathing in the bath house. I can assure thee that the Hierophant kept it close to his breast, even during his leisurely strolls through the park...");
	say();
labelFunc02C1_027A:
	if (!(var0000 == 0x0064)) goto labelFunc02C1_029C;
	message("~~ ~~REPORT ON THE SHASRAJAH~~ ~~by Jaljashram~~");
	say();
	message("  O Great Hierophant, sorrow fills mine heart to tell thee the regretful news that our great hope, the Shasrajah, cannot be counted on to attach the venomous fangs of victory about the necks of our enemies. Our great experiment hath failed.~");
	say();
	message("  As thou hast already been told, we had found a means by which the minds of our finest warriors and the bodies of snakes could be fused with one another. The resulting warrior would wreak terrible havoc on the forces of Order, bringing them their well-deserved destruction. In the earliest stages of the experiment all was well; we succeeded in joining Adder with Man in five of seven volunteers. The resulting form was vaguely humanoid, with resilient green skin, tough as the scales of a serpent.*");
	say();
	message("  We found that the soldiers' minds were very much unchanged, and coupled with the quickness and sensitivity to smell of the adder, the Shasrajah were formidable in battle. Their long necks had tremendous reach, and they preferred to attack solely with their strong jaws. We were encouraged by this success, and accepted eighty-three more warriors to undergo the metamorphosis. All was well, as seventy-one survived. We believed we had found a counter to the automaton warriors the forces of Order had reputedly developed.~");
	say();
	message("  Much to our chagrin, however, our experiment went awry shortly thereafter. As we had them do battle to assess their powers, we noticed a disturbing trait -- the warrior would become more bloodthirsty and uncontrollable with each triumph! Soon they began to rebel against our commands. We had no choice but to exterminate them and begin anew, but the five hundred soldiers we sent against our own creations -- our monsters -- were unable to best them. We surrendered the area to them, enclosing them with stout doors in the corridors leading out.*");
	say();
	message("  I can only assume that they have died. O Great Hierophant, I would recommend never performing these experiments again; they are more potentially dangerous than they are potentially helpful...");
	say();
labelFunc02C1_029C:
	if (!(var0000 == 0x0065)) goto labelFunc02C1_02AA;
	message("  In memory of the countless soldiers who sacrificed their lives in the War of Imbalance");
	say();
labelFunc02C1_02AA:
	if (!(var0000 == 0x006F)) goto labelFunc02C1_02C8;
	message("~~Servants of Order~~ by Isstherios~~");
	say();
	message("\tOver the years, we who follow Order have devised a number of ingenious servants to simplify our lives.  The earliest attempt is known as the \"Animated Suit of Armor\".  Though automatons have made these nothing more than curiosities, some functional units are still in use today (e.g. the Fiend's Domain, but I implore you not to go exploring just to see one) The animated suits of armor have picked up many knicknames, such as \"Suits,\" \"Brass-brains,\" \"Dummies,\" etc.  They are severely limited in capability, able to understand but a few words, and even then are more than likely to forget orders more than three words in length.  They were used primarily as guards, for they could take more damage than a human guard and were replaced easier if slain than a man would be.*");
	say();
	message("\tThe next achievement, representing a significant leap in servant design, was the \"Brass Automaton.\"  These are still used (particularly by frontier outposts such as Serpent's Fang) because they are far more intelligent than animated suits of armor and less costly to create than iron automatons (see next page).  Their main drawback is that, like the animated suits of armor, they cannot be re-used once they are slain.*");
	say();
	message("\tMost commonly used are the \"Iron Automatons.\"  Since they are considered the standard servant in our time, they are referred to simply as automatons. Iron automatons are slightly stronger, quicker, and more resilient than brass automatons as well as slightly more intelligent.  The greatest advantage, however, is that if an iron automaton is slain, it can be reactivated. The spell used, Create Automaton, is found in nearly every wizard's spellbook. These advantages do not come free, however; they are more costly to initially create and drain more mana and reagents than the lesser servants.*");
	say();
	message("\tThe greatest of all the automatons are not servants at all.  The Lords of Discipline are automatons with the minds of the greatest warriors transferred into their bodies.  They are unsurpassed in strength, speed, intellect, and resilience, and have thus far proven to be the determining factor in the war. It is to this culmination of our knowledge that we, the followers of the Serpent of Order, shall emerge triumphant in our struggle with the misled followers of Chaos.");
	say();
labelFunc02C1_02C8:
	if (!(var0000 == 0x0078)) goto labelFunc02C1_0322;
	message("STRENGTH THROUGH ETHICS~~ by Sheshemenien~~");
	say();
	message("\t\t\tDear reader, I intend this essay to be a guide for thee. For thou art what thou dost do. Thou dost do what thou dost judge best for thyself. But, in this matter, is thy judgement as clear as the sky on a summer day? That is the question. If thou canst not answer without a reasonable doubt, thou needest to be enlightened. The purpose of this essay is to increase thy strength through enlightenment. Ethics will enlighten thee.*");
	say();
	message("\t\t\tStrength is to the adventurer what milk is to the newborn.");
	say();
	message("Without it there is no growth, only dwindling and loss of Life.");
	say();
	message("The path to fulfillment is a long climb towards the heights of the highest and greatest mountain of all.");
	say();
	message("Herein, I will show thee that there are no shortcuts, and the rewards awaiting thee are abundant.");
	say();
	message("Be frugal and be prodigal.");
	say();
	message("In order to receive, thou hast need to give, give, and give again. Allow me to clarify this. Do not misunderstand my words. Do not expect to receive something in exchange for thy gift. Thy gift must come from thine heart. If thou dost expect the recipient to thank thee, thou art on the wrong path. Thou shalt thank the recipient.");
	say();
	message("Meditate upon those words of wisdom and thy strength will grow with thee.*");
	say();
	message("Show respect for all life forms. Unless they do attack thee, spare them.");
	say();
	message("Be blameless and upright. Being sincere and fair in all of thy transactions will provide thee with more power than thou ever hadst. Thou wert strong, thou wilt be stronger. Thy strength will be exalted in truth.");
	say();
	message("Be great amongst the multitude of thy brethren. Relieve commoners and seek their welfare.");
	say();
	message("Be humble. Talk no more so very proudly, let not arrogance flow from thy mouth like wisdom from the fountains of Spinebreaker.");
	say();
	message("Thou shalt not use thy tongue to deceive. Remember to practice whatever thou dost advocate.");
	say();
	message("Quality should be thy rule. Quality of craftsmanship if thou art a craftsman, quality of the time spent with thy brethren, quality of the words thou speakest, quality in thine actions. Quality secures thine ascent above the multitude.");
	say();
	message("Be patient in all circumstances. That will make thee wealthy, for each minute is a priceless gem.");
	say();
	message("Remember that water and ice are two facets of the same element. Be that element. Like water avoid obstacles as large as mountains. Like ice provide a solid path between two banks. Rush like water to extinguish a fire. Avoid fire as unto ice.");
	say();
	message("Strength feeds on Ethics and Ethics on strength.");
	say();
	message("When trouble and anguish come upon thee, Ethics will give thee the strength to overcome.");
	say();
	message("By this thou shalt overcome.");
	say();
labelFunc02C1_0322:
	if (!(var0000 == 0x007D)) goto labelFunc02C1_03FC;
	message("~~ ~~ THE STRUCTURE OF ORDER");
	say();
	message("~A collection of the Principles of Order~");
	say();
	message("~~compiled by Shaashaanna*");
	say();
	message("\tThe Philosophy of Order is based upon the Three Forces of Order.");
	say();
	message("The Philosophy of Order is a set of principles meant to lead thee");
	say();
	message("on the path toward strength through enlightenment.");
	say();
	message("The Three Forces are as follows:~");
	say();
	message("- Ethicality~");
	say();
	message("- Discipline~");
	say();
	message("- Logic~*");
	say();
	message("\t\t  ~Most righteous reader, let us examine the structure of Order as it appears through the Forces of Order and the underlying principles of the philosophy of Order.~");
	say();
	message("\t\t\t\tETHICALITY");
	say();
	message("\t\t\t\t~What is Ethicality?");
	say();
	message("Ethicality is the belief in abiding by rules of conduct.");
	say();
	message("Those rules must be in thy mouth, in thy mind and in thine heart at all times. Doing so thou wilt understand thou art those rules. ");
	say();
	message("The rules are the Forces. The rules are not a part of thee, they are thee and thou art the rules.*");
	say();
	message("Once those rules, or Forces, are one with thee, then, and only then, canst thou abide regardless of the circumstances.");
	say();
	message("Those rules of conduct are not too difficult for thee; neither are they distant so that thou art not able to achieve them. Those rules of conduct are within thy reach. Moreover, they are necessary if thou dost not wish to be torn and slain by beasts.");
	say();
	message("Beware, dear reader, for the beasts of Chaos are watching each of thy steps.");
	say();
	message("Thou shalt perform the words of the Philosophy of Order that are written herein if thou art to live as a man.*");
	say();
	message("\t\t\t   DISCIPLINE");
	say();
	message("\t\t\t\t~What is Discipline?");
	say();
	message("Discipline is the ability to finish what one hath begun, and to");
	say();
	message(" not be distracted.");
	say();
	message("Persevere, dearest reader, persevere!");
	say();
	message("Listen carefully to these words and let those principles be with thee.");
	say();
	message("Listen to silence and it will speak to thee.");
	say();
	message("Discipline is patiently rebuilding thine house washed away by a solstice flood. In other words, Discipline is not surrendering thy quest even though some of thy precious belongings have been eroded or destroyed.*");
	say();
	message("\t\t\t\tLOGIC");
	say();
	message("\t\t\t\t~What is Logic?");
	say();
	message("Some will tell thee that Logic is 'a little bird chirping in a meadow' or that it is 'a wreath of flowers which smell bad'. Do not lend thine ears to their confusing messages.");
	say();
	message("We say, dearest reader, that Logic deals with two states in the Land of Thought: true and false.");
	say();
	message("Thou shalt realize that:");
	say();
	message("Logic is mightier than magic.");
	say();
	message("Logic turns darkness into bright daylight.");
	say();
	message("Logic will illuminate the tunnel of ignorance for thee. It will bring thee confidence and knowledge.");
	say();
	message("Logic is the ability to think clearly and to reason to a conclusion, without emotional bias.");
	say();
	message("Logic is the power from within which will infallibly guide thee");
	say();
	message("throughout various realms across time and waters.*");
	say();
	message("With the Three forces of Order, wisdom and might are on thy side, dear reader.");
	say();
	message("Once thou dost have the Forces of Order in thy life thou shouldst have no fear.");
	say();
	message("Once thou dost have the Forces of Order in thy life thou shouldst have no doubt.");
	say();
	message("Once thou dost have the Forces of Order in thy life thou shouldst have no emotion.");
	say();
	message("Moreover, neither bias nor conceit affect thee.~");
	say();
	message("\t\tWill it be well with thee when thou wilt be put to trial or");
	say();
	message("wilt thou let Chaos overcome thee?");
	say();
	message("Chaos is wrong and hath no place within our philosophy.");
	say();
	message("Do not attempt any sort of combination for thou shalt count");
	say();
	message("Balance as thine enemy.");
	say();
	message("\t\tRespect those words for they are words of wisdom.");
	say();
	message("\t\tHonor the Great Serpent, for he taught us this system for the benefit of all.");
	say();
	gflags[0x0252] = true;
labelFunc02C1_03FC:
	if (!(var0000 == 0x0082)) goto labelFunc02C1_0492;
	message("~~ ~~HOLY BOOKS OF THE OPHIDIANS ~~*");
	say();
	message("Our Sacred Books will reveal to thee what thou must know to live");
	say();
	message("the life of a true Ophidian.");
	say();
	message("Respect The Books for They were written with the pain, the blood and");
	say();
	message("the hopes of thine ancestors.");
	say();
	message("Read our Books to know thyself.");
	say();
	message("Thou shalt be clean when touching The Books.");
	say();
	message("Thou shalt be pure when reading The Books.");
	say();
	message("Thou shalt read The Books aloud.");
	say();
	message("Thou shalt not say with thy tongue that which thou wouldst not make good with thine actions.");
	say();
	message("Now, thou mayest proceed.*");
	say();
	message("~Herein lies the tale of the Ophidians.");
	say();
	message("The Ophidians are the inhabitants of this continent.");
	say();
	message("In the First Age, the world was divided into four continents. There was no magic in the land, and two Kings ruled in peace. This was before the Enlightenment came to us.");
	say();
	message("Then came a great war, and the Four Lands were sundered from one another. Then, we were alone.");
	say();
	message("The Destruction was great. One Kingdom fell when its liege died while abroad. Madness took the King of the White Dragon.*");
	say();
	message("Then the Great Earth Serpent spoke to us! Our people built beautiful cities in safe places under the ground. Six temples were built, and three special Shrines. The Serpents lived among us.");
	say();
	message("This was our world.*");
	say();
	message("\tThis was the time after the defeat of Mondain, when our spiritual leader The Great Hierophant of The Ophidians explained the changes in the Universe through our ethical philosophy of Balance, and its twin properties of Order and Chaos. The Serpent spoke to us through him. The Great Hierophant was the only one who could open the Wall of Lights. The Wall of Lights is the entrance into the Void. He entered the Void to speak with the Serpents.");
	say();
	message("Our temples and shrines were organized in the following manner:");
	say();
	message("~The Three Grand Shrines");
	say();
	message("~The Chaos Temples");
	say();
	message("~The Order Temples");
	say();
	message("The total number being nine.*");
	say();
	message("The Three Grand Shrines were divided into Balance, Chaos and Order.");
	say();
	message("\t\tThe Chaos Temples were divided into the Temple of Emotion, the Temple of Enthusiasm, the Temple of Tolerance.");
	say();
	message("\t\tThe Order Temples were divided into the Temple of Ethicality, the Temple of Discipline, the Temple of Logic.");
	say();
	message("\t\tThe six temples had sub-leaders:~the Master of Ethicality, ~the Master of Discipline, ~the Master of Logic, ~the Master of Emotion, ~the Master of Enthusiasm, and ~the Master of Tolerance.");
	say();
	message("\tDuring ceremonies, the Great Hierophant was assisted by the Order Hierophant and the Chaos Hierophant. Rich jewelry and shining armour were worn at that time. Throughout the years we had different successors in charge of those functions. The deceased Great Hierophants were buried on the Isle of the Crypts.*");
	say();
	message("Then came the Disaster. The Great Earth Serpent was taken from the Void, no longer to communicate with us! We became obsessed with the struggle between Order and Chaos. No more Balance!");
	say();
	message("\tThe Great Hierophant was murdered and his sacred artifacts were plundered by zealots of Chaos.");
	say();
	message("Rivalry corrupted the hearts and minds of our people. The reigns of belligerent factions began. War broke out. Armies marched, cities were laid waste, and lava flowed from the deep. The Chaos people were defeated. This is when the Chaos Serpent was brought from the Void and split into three Forces. Lest they should wander the world, they were imprisoned at the three Temples of Order.*");
	say();
	message("\tThe scourges of war, earthquakes, and volcanic eruptions with their lava flows and destruction reduced the isle to a desolate land.");
	say();
	message("\t\tThereupon, the Order people left the land of their Ancestors known as Serpent Isle in search of a better place. This is a foolish quest.");
	say();
	message("I alone, a servant of Balance, am left. I soon will die. All is Death, and the land forsaken.");
	say();
labelFunc02C1_0492:
	if (!(var0000 == 0x00D5)) goto labelFunc02C1_04B8;
	message("~~ ~~MY LIFE AND MY BELIEFS~~ ~~by Svenjaja~~");
	say();
	message("I do not have much time left. I hope it will be enough time to write everything down, before THEY come for me. And THEY will come...~");
	say();
	message("I came here to this Temple full of love and inspiration. All I wanted was to read the writings of artistic truth. The wise men would talk to me and I wanted to listen to them. But then it happened...~");
	say();
	message("I did everything right, I followed the rules, but I still got confused. After fasting for two days in the meditation room and staring at the red and black floor, I was still waiting for a sign. A sign which would show me the right path to follow.~");
	say();
	message("And finally, I could rejoice. I found my calling and I was taken to the Pool of Dedication. But then the soldiers came and destroyed everything. They killed the Great Hierophant of Chaos in the garden. Somehow the people saved the Sceptre of Enlightenment. They were able to hide it beneath the lectern...~");
	say();
	message("I hope for the safety of my brother Sethys, for he doth have the key to the Altar of Tolerance. The Great Hierophant had entrusted him with the key, before the soldiers arrived...");
	say();
	message("I cannot hope for mine own safety, for I am sitting here now, awaiting my death. The Order fanatics will come soon and with them my death is arriving...");
	say();
labelFunc02C1_04B8:
	if (!(var0000 == 0x005C)) goto labelFunc02C1_04D6;
	message("~~ ~~AND LIGHT THERE WILL BE~~by Sasoshi, the Mage~");
	say();
	message("The Ophidians have been living too long in the darkness. I have been experimenting with different compounds and different ingredients to find a way to create light, light that lasts much longer than the artificial light that we have. It hath taken me years and years of my life. There have been many accidents with all the devices and the lighting of the Magic Candles. The candles will announce this celebration throughout the sky.~");
	say();
	message("He who follows the Ways of Balance will shine.~");
	say();
	message("He who shines will pass the Trials of Fire and Ice.~");
	say();
	message("He who passes the Trials will enter the Antechamber of the Grand Shrine.");
	say();
labelFunc02C1_04D6:
	if (!(var0000 == 0x0049)) goto labelFunc02C1_04FC;
	message("~~ ~~THE DOCTRINE OF CHAOS~~by Vessuvius~");
	say();
	message("I believe in the Forces and Powers of Chaos.");
	say();
	message("I believe in the ways of Tolerance, Enthusiasm and Emotion.");
	say();
	message("I believe that those ways will show me how to better myself and therefore how to better my life.");
	say();
	message("I believe that believing in Tolerance will teach me the acceptance of all things.");
	say();
	message("I believe that believing in Enthusiasm will teach me the source of the energy which will allow me to accomplish great tasks.");
	say();
	message("I believe that believing in Emotion will give me the ability to perceive feelings which come from the heart and not the mind.");
	say();
labelFunc02C1_04FC:
	if (!(var0000 == 0x004F)) goto labelFunc02C1_051A;
	message("~~ ~~DEVOTION~~by Eshrashardt~~");
	say();
	message("The Forces of Order must be stopped. We cannot go on like this much longer. We hope that our beliefs in the Forces of Chaos will help us to survive. If we are able to survive, then our devotion to Enthusiasm will be rewarded in the world beyond our lives. We can hear the Void calling our names. We know we need to follow, but we are not ready yet. We must stop Order first. That must be the purpose of our being here. If we are successful then we can leave this world without feeling guilty. If we stop Order then our lives have not been wasted here. We need to accomplish our task to be able to prove our worthiness. Only in that do we see a way to truly show our gratitude.");
	say();
	message("SIGNED: Iljosha");
	say();
	message("SIGNED: Shamshellar");
	say();
	message("SIGNED: Eshrashardt");
	say();
labelFunc02C1_051A:
	if (!(var0000 == 0x0050)) goto labelFunc02C1_0530;
	message("~~ ~~THE SERPENT LAMP POSTS~~by Sivashvos~~");
	say();
	message("These majestic sculptures, each a great snake poised triumphantly with its mock prey, a shining magical globe, in its mouth, are signatures of our cities.  We owe these magnificent light-bearing monuments to a spellcaster who went by the name Eshalveras. It was he who first poised a light globe on a statue of a serpent, making these statues holy reminders of those we owe our being to, but also functional parts of our cities. I was granted, for purposes of recording for posterity the events of our times, the opportunity to converse with this brilliant mage so as to provide insights into his remarkable creation.");
	say();
	message("Eshalveras revealed to me that it was naught but three reagents combined to form the luminous mineral which acts as long-lasting fuel for the lamps. All of these, Agnium, Serpentinium, and Zerine, can be found in many wizards' labs, and certainly in Eshalveras' lab within the Conjury. The true magic lies in the pedestal, nondescript in appearance but powerful in magic. The reagents, when placed on the pedestal, fuse to form the light mineral, which can then be used in the lamp posts. Eshalveras is truly a remarkable man; he was able to relate to me many exciting tales of dweomercraft in our day...");
	say();
labelFunc02C1_0530:
	if (!(var0000 == 0x0053)) goto labelFunc02C1_0542;
	message("~~THE GREAT HIEROPHANTS~~by Zavajorish~");
	say();
	message("The first Hierophant ever to commission a pair of our Temples was Sheshevra. He was selected because of his outstanding qualities of leadership and his overwhelming sense of Harmony. He commissioned the Temples of Tolerance and Ethicality. The Ophidians needed a spiritual leader like him to teach them the doctrines of Balance. He was responsible for the Temples and their ways of belief. He was given the authority to perform all important ceremonies of the Serpent People, known as the Ophidians.");
	say();
labelFunc02C1_0542:
	if (!(var0000 == 0x0054)) goto labelFunc02C1_0554;
	message("~~THE GREAT HIEROPHANTS~~by Zavajorish~");
	say();
	message("The last Hierophant to commission a pair of our Temples was Sessessej. He was selected because of his outstanding qualities of leadership and his overwhelming sense of Rationality. He commissioned the Temples of Emotion and Logic. The Ophidians needed a spiritual leader like him to teach them the doctrines of Balance. He was responsible for the Temples and their ways of belief. He was given the authority to perform all important ceremonies of the Serpent People, known as the Ophidians.");
	say();
labelFunc02C1_0554:
	if (!(var0000 == 0x0055)) goto labelFunc02C1_056E;
	message("~~THE VOICE~~by Shavazoss~~");
	say();
	message("With this book I want to express my pride. I am one of the few that are allowed to serve our Great Hierophant and I am proud to serve him. He is one of the few people left in these days who know what life is about. His wisdom and his leadership have shown me the purpose of life. To serve him is quite an experience and I am very thankful to be the one who is blessed with the duty. He hath told me about many events in his life and I want to share these with thee. At one point in his life he visited the Isle of Balance, which is also known as Sunrise Isle. He hath climbed the mountain there to the top. And that is where the most amazing of his stories took place. On top of that mountain he heard the voice of the Great Earth Serpent. The Great Earth Serpent told him to commission the building of the Serpent Gates and the three Grand Shrines...");
	say();
	message("Believe me reader, when I listened to this, I shuddered with awe...");
	say();
	message("I still cannot believe that I am the one chosen to be his servant. What a blessing it is...");
	say();
labelFunc02C1_056E:
	if (!(var0000 == 0x003D)) goto labelFunc02C1_0580;
	message("~~AT EASE~~Handbook for the Commissioned Soldier~~by Sharzshov~");
	say();
	message("This handbook will help the Commissioned Soldier to realize how important it is to know how to handle the masses of lower rank soldiers. Only a well trained army is capable of winning a war. The only way to have a well trained army is through the Commissioned Soldier. He is responsible for the training, dedication and devotion of his troops. This is not a training manual. This handbook merely emphasizes the importance of authority. Only the strong and strict leader will receive the respect from his troops that a good leader deserves. Only troops which are willing to take orders are good troops. Therefore troops will follow only orders that are given by a strong leader whom they respect. Conclusion: there is only one rule on how to train masses of soldiers: Showing strength and authority to the lower rank soldiers, the noncommissioned troops. Only the Commissioned Soldier that interacts on a strong and strict basis with his troops will lead them to victory in combat...");
	say();
labelFunc02C1_0580:
	if (!(var0000 == 0x003F)) goto labelFunc02C1_059A;
	message("~~DISCIPLINING SOLDIERS~~by Sethmantih~");
	say();
	message("~\tIt hath become necessary to create a means of disciplining our soldiery. Though the soldiers we are given to work with are generally obedient and disciplined, on occasion an unruly soldier will appear in the ranks. It would be foolish to merely dismiss this able-bodied man, for in these times of war every hand capable of holding a sword must do so. Nay, dismissal is not the answer.");
	say();
	message("~\tWhat, then, are we to do with those who resist the teachings of discipline? By what means may we save this soldier from the lure of Chaos and place him firmly back on the path toward being a useful implement with which to smite the Chaotic forces?");
	say();
	message("~\tWith these questions our Master did challenge the wisest men in the Temple. I, Sethmantih, did solve these challenges...");
	say();
labelFunc02C1_059A:
	if (!(var0000 == 0x0040)) goto labelFunc02C1_05BC;
	message("~~MY JOURNEY~~by Shartmannah~");
	say();
	message("On my journey to find the Serpent Fountain I was troubled many times with doubt about my quest. Was I doing the right thing? Was I taking the correct path? How much longer could I resist the urge to accept failure?");
	say();
	message("I hunted through the master's chambers, stared into the coffins of those who once cared for the temple, and searched the library for the keys and implements necessary to complete the quest. The Master would only tell me two things; that I would have no reason to leave the temple, and that somewhere on the path my discipline would be tested.");
	say();
	message("I speak only in generalities, lest my words be seen by the wild eyes of one undisciplined. I doubt not that such a person would die on the way to the water, but there are wards against death in all its incarnations.");
	say();
	message("My discipline was indeed tested, and tested harshly. The key to completing my quest was perseverance. I had to search the same place many times and not admit defeat; I had to discipline my mind to keep it from wandering. The hardest part of the path to the fountain lay just before it, and I bear the scars on my feet, but, as is taught here, if one can only discipline the mind, the body can then be trained. I pushed the pain from my mind, so that I did not feel the acid searing my flesh, eating away at my skin. When finally I did reach the fountain, the test was not over -- to return to the temple proper, I had to brave the acid again.");
	say();
	message("The test made me strong, obedient, disciplined. Had I failed, I would be as one of those whose hearts I seek to skewer; chaotic and undisciplined. Due to the lessons of discipline I had learned, I was able to not only force the pain from my mind as the acid tried to eat my legs away, but steel my flesh against it so that now only the soles of my feet bear mild scars...");
	say();
labelFunc02C1_05BC:
	if (!(var0000 == 0x005E)) goto labelFunc02C1_05CE;
	message("~~ ~~THE BOOK OF THE FELLOWSHIP~~ ~~by Batlin of Britain.*");
	say();
	message("     Good morning to thee, gentle friend and traveller! No matter what time of day it might be when thou art reading this -- no matter what the hour of the clock -- I say good morning to thee because this very moment brings to thee the coming of the dawn. The dawn, as everyone knows, is the moment when illumination comes. The dawn marks the end of the long dark night. It is the moment that marks a new beginning. It is mine humble hope that these words may be for thee a dawning, or at least, a sort of awakening...");
	say();
labelFunc02C1_05CE:
	if (!(var0000 == 0x005F)) goto labelFunc02C1_05F0;
	message("~~ ~~LORD BRITISH~~The biography of Britannia's longtime ruler~~ ~~ by K.Bennos*");
	say();
	message("     ...While many may remember that Lord British was once but one of eight monarchs (back when the lands were known as Sosaria), few are aware that he is not even a native of our own lovely Britannia. His origin is from another world, one from which he entered ours by way of a red moongate. (In fact, it is through this same type of gate that the Avatar of legend purportedly enters Britannia.) As ruler of one of the eight kingdoms, he was instrumental in selecting a champion to face Mondain, Minax, and Exodus.~");
	say();
	message("     When the terrible machine, Exodus, was defeated, 'twas Lord British behind whom all the people of Sosaria rallied. The unified land become known as Britannia, with Lord British as the sole monarch. Though never let it be said he rules with a tyrannical hand. His reign hath always been one of Truth, Love, and Courage, supported by his utmost belief in the eight virtues.~");
	say();
	message("     It was Lord British who had the insight to call forth a quest for the Avatar (who also happened to be the champion from the days of Sosaria), and who gave prosperity and happiness unto the people.~");
	say();
	message("     Then came his mysterious disappearance, when the Stranger who became the Avatar was called by his companions to aid in the search for the lost monarch. Note how Lord Blackthorn, affected by the Shadowlords, quickly turned Britannia's fair lands into a place of terror. But find our noble Lord the Avatar did, and Britannia was restored to its former, peaceful state.~");
	say();
	message("     Then came the Gargoyles, and our honorable sovereign thoughtfully requested the return of the Avatar...");
	say();
labelFunc02C1_05F0:
	if (!(var0000 == 0x0041)) goto labelFunc02C1_0602;
	message("~~THE WAR OF ORDER AND CHAOS~~by Ssanettess~~");
	say();
	message("No one truly knows what happened to cause the war between the Forces of Chaos and Order about 300 years ago. No one can say for sure that he knows which devilish thoughts possessed people to fight each other when they were supposed to love each other and treat each other with respect. But everyone hath been paying for it since the war ended. The Order Forces won the war, and imprisoned the Chaos Forces. But what exactly did they win? It seems that they miss their brothers and sisters now. And who is to say that the Order Forces enjoyed throwing the Chaos Forces into confinement. Going back to the days before the war, living in peace with the Chaos Forces would be a dream come true for me...");
	say();
labelFunc02C1_0602:
	if (!(var0000 == 0x0042)) goto labelFunc02C1_0618;
	message("~~THE SYMBOL OF DISCIPLINE~by Sharless~~");
	say();
	message("The Symbol of Discipline is a reminder of what we, the Initiates of Discipline, must strive for. Consisting of three prongs, they symbolize the following: Mind, Body, and Environment. The mind is the first level of discipline; without Discipline of the Mind, one cannot master the other levels of discipline. Discipline of the Body is the second level of discipline, for one cannot master one's surroundings without first mastering one's self. The third branch of the symbol represents Discipline of Environment. This branch, added to represent the superiority of Order, justifies the military's presence here; if one can master one's self, one can then master the world around him, and drive Chaos out from his environment.");
	say();
	message("The symbols here in our temple are not mere inspiration, however. The Altar before the serpent statue doth have upon it two slots. In order to insure the security of our temple, the automatons are aided by a safeguard against defilers -- bolts of lightning fire from the altar unless the quartz symbol is placed in the slot on the left side. A bridge spanning the water around the statue is called into being if the obsidian symbol is placed in the right slot; if it is not there, none can gain access to the Water of Discipline.");
	say();
labelFunc02C1_0618:
	if (!(var0000 == 0x0044)) goto labelFunc02C1_062A;
	message("~~THE BOOK OF DISCIPLINE~by Shrosvitash~");
	say();
	message("The ultimate wisdom of life may only be reached through discipline. It takes strength and concentration to follow the guidelines of discipline. Therefore the weak and distracted mind will fail. The weak and distracted mind will not have the power to succeed. And only that power will take thee to the top. But there is no\troom for the weak at the top. Only the strong mind will find a place there.");
	say();
labelFunc02C1_062A:
	if (!(var0000 == 0x0045)) goto labelFunc02C1_063C;
	message("~OUR GREAT LEADERS~by Shilonar~~");
	say();
	message("The religion of our great nation must have leaders, worthy leaders. There are things, events and ceremonies, that require a person of great trust. The nation hath decided to choose trustworthy people for those positions and give them certain ranks. Full of respect do we call the leader of the Shrine of Balance our Great Hierophant. Only the Great Hierophant can perform the important ceremonies at the Grand Shrine of Balance. During those ceremonies, however, he receives help from the leaders of the Shrine of Order and Chaos. They have the rank of Order Hierophant and Chaos Hierophant. All three have assistants to help them with their duties; these are the sub-leaders. These assistants are of high rank also and we give them the title of Master. These Masters are the leaders of our Temples. Each one of them is authorized to perform ceremonies in their own Temple.");
	say();
labelFunc02C1_063C:
	if (!(var0000 == 0x0046)) goto labelFunc02C1_064E;
	message("OUR BLESSED SERPENT ISLE~by Shovaresh~");
	say();
	message("Our beloved Serpent Isle is the prettiest country there is. No place can be more enjoyable for mankind. It is so peaceful. There is no anger or distrust in the population. Everything is balanced, people live together well. There cannot be any other place in any other dimension that could possibly be more peaceful or more blessed with beauty. Only balance is responsible for the well-being of this country. Only balance makes it possible for people to live together in peace. Only balance will provide good harvests, which provide enough food. People that have enough to eat are happy and do not have to worry whether they are going to live to the next day. Balance is the ultimate way to freedom and peace. The beauty of our country cannot be put into words. One must go and discover it for himself.");
	say();
labelFunc02C1_064E:
	if (!(var0000 == 0x0047)) goto labelFunc02C1_066C;
	message("IS THERE HOPE?~by Shovaughana~");
	say();
	message("I do not know what to do anymore. I am desperate. We are all going to die, I know it. I and my children are going to die and there is no way for me to protect mine own flesh and blood...~");
	say();
	message("It all began with the soldiers entering the city. Without any warning they attacked us. They began to kill people immediately, the elderly, the children and us women. Those heartless and cold-blooded bastards do not care...");
	say();
	message("Mine only hope is that our men will return in time to defend and protect us. Our food supplies are frighteningly low. Soon we all will be starving. I am already eating only the bare minimum. All my rations I give to my children, hoping that they will survive until our rescuers arrive. I need to support them in every way I possibly can, they are our future -- they are my life. I could not forgive myself if anything happened to them...");
	say();
	message("I do not know if I have the strength to wait for the rescue. If there is no chance for us to survive and wait for them, I will have to choose. The choice is between letting those murderers enjoy us -- or else...");
	say();
labelFunc02C1_066C:
	if (!(var0000 == 0x0048)) goto labelFunc02C1_068A;
	message("WAR OF IMBALANCE~by Suranniss~~");
	say();
	message("This shall be the last entry I make before following my kinsmen to a better life. 'Tis appropriate, I think, that I use a newly bound book with the finest vellum; after all, it may be an Age or more before 'tis found -- if ever.~ Before I continue, I should write a few words about mine homeland -- Serpent Isle.~");
	say();
	message("Before the War of Imbalance, the dreadful war that did tear asunder our beloved homeland, Serpent Isle was a fair land indeed.~ The land was in Harmony: our people were at peace -- secure within our glorious subterranean cities. The arts prospered under the generous patronage of our most beloved Hierophant, blessed be his name, and no citizen went hungry or was bereft of a home. We were content and happy; we had no reason to suspect that our happiness would not continue indefinitely. We were so naive.~ The War of Imbalance started simply enough, but by the time 'twas over most of our people were slaughtered, our cities devastated, and the land laid waste.~");
	say();
	message("I have been lucky, for I have survived to write about the tragedy. I cannot say the same thing about many of my friends -- they are all dead.~ Even as I write, the Adepts are scurrying about, preparing for the great ceremony that shall energize the Wall of Lights. Soon, I and my surviving comrades shall leave our shattered land, never to return. I am afraid of the future, but I know I cannot live in the past. I can only remember the past. I shall strive to remember the times of joy and try to forget the ashen, bitter memories of the war.~ The Adepts are ready, they have begun the ceremony. I feel a great surge of power! The light! 'Tis blinding! The Adepts have succeeded. The Wall of Lights is so beautiful...");
	say();
	var0001 = true;
labelFunc02C1_068A:
	if (!(var0000 == 0x004C)) goto labelFunc02C1_06B0;
	message("A TREATISE ON THE CONSTRUCTION OF LIVING GEMS~~ by Ssyorsik~~");
	say();
	message("\tThe construction of living gems requires many a component as well as Pure Discipline.");
	say();
	message("This Treatise contains the exact formulae and incantations which thou dost perform in order to succeed in the construction of living gems.");
	say();
	message("The magical fabrication of gems is one thou shouldst be warned about. For thee and thy kindred, make no attempt if thou dost doubt thy magical powers.");
	say();
	message("Ice Worms are to be found. The Ice Worm doth have to be destroyed. Then wrest its heart from the body. The Worm Heart is cold and hard.");
	say();
	message("The soul of brave warriors who fight magnificently in combat within the Harvest Moon period, or any equinox, escape the battlefield and may be contained within such a gem. Hence the name 'living gem'.");
	say();
	message("Once infused with the soul of a glorious warrior, such gems are placed inside the automatons. This is what gives them true life.");
	say();
labelFunc02C1_06B0:
	if (!(var0000 == 0x004D)) goto labelFunc02C1_06C2;
	message("~~THE TRUE BELIEVERS~ by Sschadams*");
	say();
	message("The true believers are not only to be found at the rituals and ceremonies. There are many poor souls out there who are pretending they do not believe in religious gatherings and activities. They want to make us believe that they do not need anyone for the sake of their souls. They are wrong, and deep down in their hearts, they know it, too. Sooner or later they will attend ceremonies. Most of them do not come back for a while, but that one appearance rouses their curiosity enough to attend again. It takes courage to admit that everyone needs some kind of belief. I understand that and I do not push for their trust. I know that deep down, underneath all that ruin, is a soul that wants to be rescued. It takes time, but I have all the time I ever need. I can wait and I will. I know that my day will come. And then I will open mine arms and welcome them into our religious community. There is room for everyone, no one will be turned away. And no one will be pressured to join us.");
	say();
labelFunc02C1_06C2:
	if (!var0001) goto labelFunc02C1_06FE;
	UI_move_object(0xFE9B, [0x0121, 0x03B7, 0x0000]);
	UI_play_sound_effect(0x0082);
	UI_obj_sprite_effect(0xFE9C, 0x0020, 0x0000, 0x0000, 0x0000, 0x0000, 0x0001, 0xFFFF);
labelFunc02C1_06FE:
	if (!(var0000 == 0x0097)) goto labelFunc02C1_0724;
	gflags[0x0227] = true;
	message("~~ ~~Body Transference~~  ~~The Ultimate Warrior~~");
	say();
	message("~    When a warrior hath demonstrated unswerving Discipline, the Order Hierophant may approve the creation of the Ultimate Warrior.");
	say();
	message("~    The candidate must be willing to cast aside his or her own body in favor of that of an undying automaton. This is the highest honor of Order... to serve as Order's warrior through all time.");
	say();
	message("~    The candidate shall be conducted to the chamber with all pomp and pageantry. Upon the left dais shall stand the inanimate automaton husk. The candidate shall ascend to the right dais after the transference button hath been pressed.");
	say();
	message("~    Once the bodies have been transferred, the Final Test of Discipline must be completed. In this, the candidate must strike down the now-empty husk that he or she formerly knew as his or her body. Until this is done, the body transfer is not complete and the process will reverse unless the organic husk is destroyed.");
	say();
	message("~    Some few candidates may find themselves unable to withstand the transference, and as such would normally be considered failures. But it is the Order Hierophant's wishes that no stigma be attached to this weakness. The candidate shall be allowed to live the remainder of his or her life in service to Order, being an exemplar in all but the Final Test of Discipline.");
	say();
labelFunc02C1_0724:
	return;
}


