#game "serpentisle"
void Func063B object#(0x63B) ()
{
	var var0000;
	var var0001;

	if (!(event != 0x0001)) goto labelFunc063B_0009;
	return;
labelFunc063B_0009:
	UI_play_sound_effect2(0x005E, item);
	UI_book_mode(item);
	var0000 = UI_get_item_quality(item);
	UI_play_sound_effect2(0x005E, item);
	UI_book_mode(item);
	if (!(var0000 == 0x00B6)) goto labelFunc063B_004D;
	message("~OBSERVATIONS OF PAIN~~ by MageLord Filbercio*");
	say();
	message("I. Introduction");
	say();
	message("~~     We have always thought of \"pain\" as the unpleasant reaction of a being's nervous\tsystem to certain environmental stimuli. But through my recent studies, I believe that I have come to understand pain as a state of mind, rather than a simple physical reaction.");
	say();
	message("     It is very easy to inflict physical pain on someone. A casual look about my laboratory will prove that. Iron maidens, thumbscrews, and racks are all useful for this purpose, but what should be done for the person who can literally accept and even ignore physical pain? In this case, a test of one's mental faculties shall be necessary. Research thy subject carefully, and discover what tears into his soul. Understand his psyche, and use what thou dost discover to help augment the physical torture.");
	say();
	message("     We will look now at a few examples. Suppose thou dost want to cause a harpsichordist pain. Thumbscrews are the obvious choice, but why not add to his experience by playing the blissful tune \"Sea Shanty\"? This should produce some very good results. Similarly, if the subject is a writer, strapping him to \"the rack\" and reading from the dismal \"Sir Trout's Plot Guide\" will have him writhing.");
	say();
	message("     Throughout these pages, thou wilt find even more insidious ways to produce pain. Read them well, and thou wilt never be disappointed with the results.");
	say();
labelFunc063B_004D:
	if (!(var0000 == 0x00B8)) goto labelFunc063B_0077;
	message("~POETRY FOR THE ROMANTIC LUTE~~ by Sir D. Dey*");
	say();
	message("\"Soliloquy\"~~~");
	say();
	message("I gave my love a chicken");
	say();
	message("   that had no bone");
	say();
	message("I gave my love a cherry");
	say();
	message("   that had no stone");
	say();
	message("I wrote my love a story");
	say();
	message("   that had no end...");
	say();
labelFunc063B_0077:
	if (!(var0000 == 0x00C9)) goto labelFunc063B_0121;
	message("~~ ~~ NOTES~~ ~~by Erstam*");
	say();
	message("Decade 1:");
	say();
	message("This is a new era for me. This newfound land is marvelous!");
	say();
	message("A great destiny awaits our people and thee, Erstam!");
	say();
	message("So much to learn from this land, I am overcome with joy. So much to learn about its fauna and flora, I must start early in the morning.");
	say();
	message("Tonight sleep is not to be found. I must go out, explore and meet the creatures of the night.");
	say();
	message("2nd Year of Third Decade:");
	say();
	message("Last night I decided to explore the catacombs of the city. I left as fast as I went in. This is not for a man of mine age. The place was filled with creatures unknown to me at this point. My mind doth not know how to describe them. The best description I can conjure is to say that they were some sort of monster, half-man half-rat.*");
	say();
	message("4th Decade, 1st Year:");
	say();
	message("I am still amazed at the variety and abundance of wildlife.");
	say();
	message("Thy grip on nature is always fragile at first, Erstam, remember?");
	say();
	message("As often as not, I would run into a monster or an unknown species.");
	say();
	message("I vividly remember, dear reader, the strange cat I encountered");
	say();
	message("tonight. It was eerie. The cat glowed like a spell. I left in great haste fearing for my life. Such a cat must have a strange effect upon us. I wonder what deranged mind created such a danger.");
	say();
	message("5th Decade, Third Year:");
	say();
	message("Found some ruins not too far from here.");
	say();
	message("Interesting discovery of a jawbone and large fangs. A relic from an ancient culture?*");
	say();
	message("7th Decade, 4th Year:");
	say();
	message("Today, I encountered a strange white-haired creature from the icy lands; it seemed to be a cross between Man and Beast.");
	say();
	message("Found the clue to how the Ophidians stepped from place to place without travelling through the space between. The answer lies in the Void!");
	say();
	message("2nd Year of the Eighth Decade:");
	say();
	message("That was the most frightening time so far. Dearest reader, thou wilt not believe me, but let me assure thee of the veracity of this tale. I was wandering in the forest at the northeast edge of town, when I heard this stentorian noise, this growl. I was petrified. Directly in front of me, a terrifying predator, the beast stood erect on its feet, towering well over mine height. Its huge claws and sharp teeth sent a chill down my poor old spine. I still shiver thinking of it when writing these words.");
	say();
	message("The creature lunged for my backpack, tore it asunder and devoured all of the honey jars I had saved for the outing.*");
	say();
	message("6th Year of Eighth Decade:");
	say();
	message("Those jealous mages stole some secrets and powers from me.");
	say();
	message("They want the Teeth, I am certain of it! I shall have to take up residence on some isle, where they cannot find me...");
	say();
	message("3rd Year of Ninth Decade:");
	say();
	message("I stood all night working on a few formulas.");
	say();
	message("Dawn already. What a chill bleak morning.");
	say();
	message("Need to throw more wood in the fire.");
	say();
	message("4th Year of Ninth Decade:");
	say();
	message("Today, icy blew the winds from beyond the Frozen Lands.");
	say();
	message("If this lasts I will have to make more dried meat.");
	say();
	message("Food is low. Need more firewood.");
	say();
	message("6th Year of Ninth Decade:");
	say();
	message("The day passed rather rapidly, uneventfully.");
	say();
	message("8th Year of the Ninth Decade:");
	say();
	message("What a beautiful sunrise!");
	say();
	message("I can almost taste the salt breeze from the sea.");
	say();
	message("How invigorating!");
	say();
labelFunc063B_0121:
	if (!(var0000 == 0x00D1)) goto labelFunc063B_01EB;
	message("~~ ~~A SHORT TREATISE ON COMBAT TACTICS & HABILIMENTS OF WAR*");
	say();
	message("~Introduction~");
	say();
	message("\t~Trusty and well-beloved adventurer, I greet thee well and thank thee for reading this short treatise.  Herein, combat tactics will be described for thy benefit in setting forth, dearest adventurer.");
	say();
	message("Thou wilt learn how to read a book and how to fight intelligently in our worlds.");
	say();
	message("\tThy safety is important for the worlds are vast enough for thee to roam freely about. Restless warrior, I know thou hast oft crisscrossed the land and oft the swamps, so think how easy a prey an injured man would be for the creatures who inhabit these realms.");
	say();
	message("~\tThe basic rule of safety in combat and in unknown territories is not to think of thyself as over-mighty. Thou mayest be witty and subtle in thy speech, but thou must be even more alert and aware of thy combat environment. Adapt to thine opponent, to the weather and to the terrain.*");
	say();
	message(" \tKnow thyself, know thine opponent. Thou shalt know thy limits. Thou shalt identify as quickly as possible what kind of creature thou art faced with so that thou canst use the most appropriate strategy.");
	say();
	message("\tFor example, know that herbivores will flee quite oft.");
	say();
	message("On the other hand, carnivorous creatures attack the weakest opponent.");
	say();
	message("Some creatures will attack at random or toward the weakest party member.");
	say();
	message("Thou shouldst expect militiamen and guards to use tactically accurate strategies. The weakest member will be attacked, flanking will be used, as well as tactical retreats, and so forth...*");
	say();
	message("\t\tAlways use logic. Creatures from the Icy Lands will be more susceptible to fire, for example, and swamp creatures are immune to poison.");
	say();
	message("When attacking foes, a good strategy is easily available to thee: thou canst always hide and shoot. Or thou canst flank and protect thyself quite well. When flanking, it is best to use some long range type of habiliment. For example, a crossbow could be given to an ally who is flanking. Make sure the ally who is flanking does not hurt any of the other members in thy group. Caution is strongly advised.");
	say();
	message("\t\tUse thine habiliment of war well. A bow always requires arrows. Ensure thou art not short of ammunition or wielding a useless weapon.");
	say();
	message("\t\tUse thy surroundings to slow thine opponents. For example, thou mayest lay down caltrops on thine enemy's path.");
	say();
	message("\t\tMost of all, always maintain a good balance between ranged and non-ranged habiliment of war within thy travelling group.*");
	say();
	message("\t\tUpon leaving a town for thine adventures in the wilderness, do stop by the various shoppes to purchase a backpack and fill it with many a variety of foods. Long trips without food will leave thee weak and more susceptible to wounds from thine enemies' attacks. Thou shalt not bypass a trainer's hall. Thou shouldst train hard to become a better warrior. Visit trainers and learn from them. Those hours spent training with masters may save thy life.*");
	say();
	message("\t\tWhile it is necessary to use armour wisely, I recommend to thee to buy armour as soon as possible. In doing so take into consideration the following qualities: weight, sturdiness, protection.");
	say();
	message("Armour may be divided into the two types appearing hereunder:");
	say();
	message("\t- antique");
	say();
	message("\t- magic");
	say();
	message("The magic armour type is almost twice as effective in protecting thee as the antique one.");
	say();
	message("Antique armour includes leather, metal scales, chain mail and metal plates. The sturdier the material, the greater the protection.");
	say();
	message("Leather armour, boots, collar, gloves and helm offer the least protection. On the other hand, they will be the lightest.");
	say();
	message("Scale armour and chain armour, chain coif and chain leggings are a bit better than leather, but not overmuch.*");
	say();
	message("Shields: a buckler or a wooden shield will provide thee with the least amount of protection in this category. A brass shield or a curved heater will provide thee with the most protection. By protection, thou shouldst understand that thine attacker will be deflected away from thee.");
	say();
	message("Amongst helms, thy choice is great and the best protection comes from the magic helm. The great helm is nearly as efficient, though. The crested helm and the caddelite helm do offer the same amount of safety.");
	say();
	message("Chain armour, chain coif, and chain leggings will decrease very little the impact of enemy blows. ");
	say();
	message("Thou wilt need a gorget and some greaves for those exposed vital areas. A kidney belt could be useful but, I must needs warn thee, of little protection.");
	say();
	message("Plate armour offers solid protection for thy money. I would recommend a pair of plate leggings as well.");
	say();
	message("The ultimate protection, in matters of armour, at this point in time, is as follows: a magic helm, a magic shield, a magic gorget, a pair of magic leggings and some magic gauntlets.*");
	say();
	message("\t\tDearest fighter, for thine ease I will divide weapons into groups. Thus, at one glance, thou mayest easily remember their efficiency. I will begin with the least damaging weapons:");
	say();
	message("\tBlowguns, boomerangs, daggers, slings, pitchforks, picks and whips have very little effect.");
	say();
	message(" A magic axe, a mace, a morning star, a two-handed axe, a spear, a shovel or a sword are of limited effect upon thine opponent.");
	say();
	message(" A scythe, a bow, a fire sword, a musket, or a two handed hammer are slightly more damaging.");
	say();
	message(" Crossbows (my favorite), halberds, lightning whips, magic bows, fire wands and fire bolts are very powerful weapons.");
	say();
	message("Find the best weapon and armour thou canst obtain.");
	say();
	message("Remember all weapons ought to be kept ready for immediate use.");
	say();
	message("One more word of wisdom:");
	say();
	message("Do not neglect thy sleeping time. Sleeping frequently will give thee the rest fighters need. An eight hour sleep will restore full strength for thee and thine allies.*");
	say();
	message("\tIf thou hast weak allies, thou shouldst know the most suitable and productive method of combat is to prompt them to attack the weakest enemy or encourage them to flee. In order to protect a weak ally, thou shouldst bestow the protection halo on them. In addition to that, thou mayest put the strongest member in thy group in charge of protecting the weakest.");
	say();
	message("\tWhen attacking foes, a good strategy is easily available to thee: thou canst always hide and shoot. Or thou canst flank and protect thyself quite well. When flanking, it is best to use long range type of habiliments, for example, a crossbow. Be sure the member of thy group who is flanking doth not hurt any of thine other allies. Caution is strongly advised.");
	say();
	message("\tThy band members armed with heavy weapons should be swift to attack the strongest opponent. Other members should follow thy guidance and attack the weakest enemies.");
	say();
	message("\t\tWhen reading a book, look for useful information and memorize it or jot it down, for thou mayest have need of it later. Read quickly, but read all pages. I cannot emphasize enough the importance of reading all of the pages of a book.*");
	say();
	message("Conclusion");
	say();
	message("~\tDearest adventurer, I beseech thee to thoroughly consider the aforesaid cautions and advice.");
	say();
	message("The reason that I wrote such a treatise is to sharpen thy fighting skills, but thou canst tell that is not a goal in itself.");
	say();
	message("My goal in using my quill is truly to convince thee with all mine heart and all mine expertise to hasten home safely once thy quest hath been completed and thy thirst for adventuring quenched.");
	say();
labelFunc063B_01EB:
	if (!(var0000 == 0x00D3)) goto labelFunc063B_01FD;
	message("~~ ~~THE SLEEPING SOLDIER~~ ~~Registry*");
	say();
	message("    ~ ~Gwenno~ ~Alinda of Monitor~ ~Batlin the Sage~ ~Draygan~~Peter of Monitor");
	say();
labelFunc063B_01FD:
	if (!(var0000 == 0x00D4)) goto labelFunc063B_021B;
	message("~~ ~~A TREATISE ON TORTURE~~by Evad, Royal Servant to the~~King of the White Dragon*");
	say();
	message("    I have been given the privilege of chronicling the King's romp through madness. As a reward, I will be slain quickly. His Majesty began with a commoner named Patric, stretching him on the rack. By his own hands, His Majesty turned the man to a babbling wretch over the course of twelve hours.");
	say();
	message("   ...After boiling the flesh from a family of farmers, His Majesty became inspired. He restrained a noble, a guest at the great banquet, upon the torture table and applied tourniquets to each of his limbs. One by one the limbs became useless strands of dead flesh. He showed mercy on the victim by killing him only five hours later by opening numerous small wounds on his person and letting him bleed to death.*");
	say();
	message("The King of the White Dragon killed his own wife by slaying a bull, slitting open the carcass, and placing her, tied securely, into the opening. He then sewed the opening shut such that naught but her head protruded.");
	say();
	message("He sat outside and watched as the carcass decayed around her and vultures and other carrion beasts picked apart the meat -- the bull's and hers...");
	say();
labelFunc063B_021B:
	if (!(var0000 == 0x00D5)) goto labelFunc063B_0245;
	message("~~ ~~PRINCIPLES OF ECONOMICS~~ ~~By Hyle*");
	say();
	message("    Economics is, simply put, the study of how an entity could most efficiently allocate its limited resources. I use the word \"Entity\" because these principles, moderately adjusted, may be applied on different levels.*");
	say();
	message("    From the largest, and consequently least detailed, level -- that of a worldwide market in which the intricacies of trade and specialization are most emphasized, to an individual business's or, smaller still, an individual's struggle to gain maximum utility from the limited funds provided by that person's livelihood.*");
	say();
	message("    Let us begin by defining some simple, underlying theories which may dictate the behavior of our target, which, for the purposes of this book, will focus on the economy as a whole. I intend later to publish a separate document on the wholly different level of business and/or individual-level economic fundamentals.*");
	say();
	message("    As is the case in any science, one must first be given a foundation upon which to build his knowledge; in this particular instance, I will refer to the \"Tower of Economic Understanding.\"*");
	say();
	message("    The market is the basis of my study. A market is not a tangible thing -- not like the marketplace at which one might trade with merchants for needs or wants (these I will define further into the book), although a marketplace is a part of the market.*");
	say();
	message("    Rather, the market consists of the consumer (the entity purchasing the resource) and the seller (the entity offering the resource for sale or trade). For example, at the aforementioned marketplace, the baker, offering a loaf of bread, would be the seller, and an entity interested in purchasing the loaf would be the consumer.*");
	say();
	message("    A market exists when there is a resource to be exchanged. A resource, in simplest terms, can be either a good or a service. A good is a tangible item -- examples include water, diamonds, and false beards. A service is something which is performed by an entity; e.g. the service a cargo ship supplies or even governmental bodies such as a standing garrison of soldiers...");
	say();
labelFunc063B_0245:
	if (!(var0000 == 0x00D6)) goto labelFunc063B_025F;
	message("~~ ~~THE DWELLERS OF SERPENT ISLE~~  ~~By Byman*");
	say();
	message("    One quarter of a millennium ago, the man-daemon Lord British impressed upon the citizens of Sosaria his Eight Virtues. Most of the citizens were deluded into believing that his way of life was just and fair. Some were strong enough to oppose his rule and fled to begin their own civilization, free of the oppressive autocracy.*");
	say();
	message("    These brave folk, led by a mage whose bravery is now sadly forgotten, ventured out to sea, with little idea as to their destination; only a firm belief that Lord British was a tyrant whose rule was not to be tolerated. Erstam led them to a large island, which was instantly christened \"New Sosaria.\" The land's name was changed shortly thereafter to \"Serpent Isle,\" after the strange ruins found there.*");
	say();
	message("    There were three principal groups who left Sosaria -- the Mages of Moon, the chivalrous folk of the Two Montors, and the folk of the port city of Fawn. Each had their own reasons for joining in the emigration: the mages because they felt that certain of Lord British's virtues were unrealistic; the Fawnese because Lord British had failed to acknowledge a ninth virtue -- Beauty; and the brave folk of Monitor because of their belief that Courage ranked above all else...");
	say();
labelFunc063B_025F:
	if (!(var0000 == 0x00D7)) goto labelFunc063B_0281;
	message("~~ ~~COURAGEOUS DEEDS~~ ~~By Andrew of Monitor*");
	say();
	message("~~ CHAPTER ONE~~  ~~The tale of Kosric and Pedigar*");
	say();
	message("\tThe brothers Kosric and Pedigar sailed with the original expedition to Serpent Isle, when the land was more unknown and mysterious than it is today. Each brother was the Lord of one of the two Montors on Sosaria, and, not content to settle for Lord British's uncompromising and misguided rule, convinced their people to set sail with the mages of Moon and the people of Fawn to the new land.*");
	say();
	message("\tLost in the history books of the other two cities, however, is the tale of what happened when the tired sojourners first set foot on this new land. The leader, a mage who went by the name Erstam (it surely could not be the same mad Erstam who performs intolerable experiments today), was given the honor of stepping first on Serpent Isle. It was then up to the leaders of the individual groups to decide who would next trod upon the unknown isle. Kosric and Pedigar claimed the right, as their group were the finest warriors among them. The Fawnese claimed it also, arguing that their beauty should mingle with the beauty of the new island before anyone else. The Moonshadian mages, being untrustworthy, teleported themselves onto the island while the other two groups were engaged in discussion, stealing the honor.*");
	say();
	message("\tThe greatest honor gone, the Fawnese and Monitorians descended the gangplank together. The Moonshadians scattered themselves like the four winds before they could be reprimanded, and the Fawnese ran to explore the beauty of the island. At that moment, emerging from the hills and woodlands, trolls began an assault on the intrepid band. Were it not for Kosric and Pedigar and their Monitorian soldiers, the expedition would have failed then and there, for the Fawnese and Moonshadians were caught unawares. However, the two launched themselves at the foes, Kosric wielding his hammer, \"Thunderbolt,\" and Pedigar with his greatsword, and brought doom upon the foul trolls.*");
	say();
	message("\tWhen the battle was over, a score of courageous Monitorians lay dead beside the bodies of twice that number of trolls. Let it not be forgotten, brave Monitorian, that it was thine ancestors who led the way for all civilized life on this island.");
	say();
labelFunc063B_0281:
	if (!(var0000 == 0x00D8)) goto labelFunc063B_0297;
	message("~~ ~~RECIPE BOOK~~ ~~By Petra*");
	say();
	message("Apple Way~ ~ 2 apples, peeled and sliced~ 1 cup sugar~ 2 tablespoons of corn starch~ 2 tablespoons of butter~ 1 teaspoon cinnamon~ 1 double pie crust*");
	say();
	message("Place the apples, sugar, cornstarch, and cinnamon into a large bowl and combine them. Put the mixture into the bottom pie crust with the butter. Put on top pie crust and cut slits for steam to escape. Bake in 350 degree oven for about 45 minutes.");
	say();
labelFunc063B_0297:
	if (!(var0000 == 0x00D9)) goto labelFunc063B_02BD;
	message("~~ ~~RECIPE BOOK~~ ~~By Petra*");
	say();
	message("Sweet Muffins~ ~ 3/4 cup milk~ 1/2 cup sugar~ 2 teaspoons salt~ 1/2 cup butter~ 1/2 cup warm water~ 5 ounces of yeast~ 1 egg~ 4 cups unsifted flour~*");
	say();
	message("Scald milk, stir in sugar, salt, and butter. Cool to lukewarm. Measure warm water into a large warm bowl. Add yeast and stir until dissolved. Stir in lukewarm milk mixture, egg, and half of the flour, and beat until smooth. Stir in remaining flour to make a stiff batter. Cover the bowl tightly with waxed paper. Refrigerate the dough at least two hours.*");
	say();
	message("Divide dough into two halves and roll each piece into a 9 by 14 inch rectangle. Brush lightly with melted butter.");
	say();
	message("Filling:~ Sprinkle the rectangle with a mixture of 3/4 cup sugar, 1 teaspoon cinnamon, and 1/3 cup raisins and pecans. Roll the rectangles so that they are 9 inches long (like a jelly roll).  Make sure the edges are firmly sealed.*");
	say();
	message("Cut each roll into nine equal pieces and place them in a greased pan (leave enough room for the pieces to expand). Cover the pan and let the dough rise in a warm place until the rolls have doubled in size. Bake at a moderate temperature (350 F degrees) for about 30 minutes.*");
	say();
	message("Frosting:~ Frost with a mixture of confectioner's sugar (1 1/2 cup) and 5 teaspoons of milk.");
	say();
labelFunc063B_02BD:
	if (!(var0000 == 0x00DD)) goto labelFunc063B_02D7;
	message("~~ ~~FIGHTING IS AN ART~~ ~~By Johnson*");
	say();
	message("~  Lesson One: ~   In fighting, thou must never lose, no matter what thou must do. Anyone fighting thee is an enemy. An enemy must be destroyed. ~\tDuring battle thou wilt be confronted by thine enemy. Thou must defeat him, or thou wilt bring disgrace upon thyself, thy clan, and thy trainer. ~    Battles are always on the horizon. Thou must train hard, and work thyself hard. Thou must think battle, eat battle, sleep battle if thou dost expect to be victorious. Those warriors who do not think they can do this should contemplate another line of work.");
	say();
	message("~   Knowing thy weapon is the greatest value. Be it sword, mace, or bow, thou must train with it until mastery if thou dost want to be a true warrior. If thou hast not the time or the mind to train in this fashion then thou shouldst perhaps train with the shovel and the carrying of animal wastes from the fields instead. It is better for thee to serve thy clan as best as thou canst, though it be a less than knight-worthy post, than for thee to run in battle and endanger thy comrades.");
	say();
	message("\t Anyone caught running away from a battle should be put to the sword immediately, lest others feel that they may let their womanish fears prevail. The true knight is not he who fights battles, but he who relishes in the spilling of blood. He who is enthralled with the smell of a bowel split wide, or the sight of anothers' blood staining his sword and armour, should be praised above all. This is what a true knight seeks. He is a true master in the arts of fighting.");
	say();
labelFunc063B_02D7:
	if (!(var0000 == 0x00DE)) goto labelFunc063B_0311;
	message("~~ ~~ Lord British's Tyrannical Adventure ~~ ~~by Anon *");
	say();
	message("~Lord British was a monarch who was haughty and vain ~And especially proud of his despotic reign. ~But conceit of this sort isn't proper at all ~And soon the old tyrant was doomed for a fall. ~One day as he viewed his subjects from on high, ~A voluptuous young wench caught his tired old eye.*");
	say();
	message("~Bending over to see, that oversexed goat ~Let his gold crown slip and fall into the moat. ~With a cry of sheer terror he jumped like a fool, ~he rushed to his ditch (it reeked like a cesspool).*");
	say();
	message("~He leaped in kersplash! and sank like a stone. ~(Everyone hoped for a new heir to the throne.) ~But alas he came up and staggered from the sewer, ~his robes smelled of offal, his breath like manure.*");
	say();
	message("~\"Why did I do that? What possessed me today? ~I'm as daft as old Iolo, and now I smell like Dupre.\" ~\"And if anyone sees me, oh what a disgrace, ~I had better leave if I want to save face!\"");
	say();
	message("~But a crowd had assembled and stared, amazed, ~the sight confused them, the stench left them dazed. ~Then with a shriek a young boy began to laugh, ~giggling and pointing at the king's fecal bath.*");
	say();
	message("~Becoming enraged, the monarch suddenly turned wild, ~He looked like he wanted to strangle the child! ~His hand turned to fist, he struck lightning fast, ~but the old poop missed, and fell on his ass.");
	say();
	message("~Not holding back, the crowd soon roared, ~The laughter was deafening. It grew till it soared. ~But the king found no humor and called for his men. ~The arrival of the guard quickly silenced the din.*");
	say();
	message("~\"For all of you who found humor in my sorrow and misfortune ~Will soon find the rack! And pain! And contortion! ~Then I will cackle as you stew and boil, ~in a pot full of lard and bubbling oil.*");
	say();
	message("~And for those who survive this (they'd liefer be dead), ~I'll pluck out their eyes, and chop off their head! ~Finally in the wind their bodies will swing, ~Then you fools will be sorry for laughing at this king!\"*");
	say();
	message("~Then all were led away at the point of a sword, ~While old Lord Brit took a dip in a ford. ~Then he laughed at the cries that screamed through the night, ~He chuckled at their anguish, he cackled at their plight.*");
	say();
	message("~In Britannia today no one openly tells this tale, ~lest they find themselves thrown in tyrant's darkest jail. ~But here in our new homeland this song can be sung, ~the tale of how British acquired his faint smell of dung.");
	say();
labelFunc063B_0311:
	if (!(var0000 == 0x00DF)) goto labelFunc063B_0327;
	message("~~ ~~The Crying Lute ~~ ~~By Gannt*");
	say();
	message("~The lute in mine hands as I softly strum, ~cries for it knows the hollow man I have become, ~of my tragedy, of my sorrow, of my lonely despair. ~Only my lute listens, alone, only it cares. ~ ~Though I am a knight, ~and mine emotions I hide, ~I still feel the soul-eating darkness inside. ~I am a man of armour and a man of the sword, ~but the blackness I feel I cannot ward.*");
	say();
	message("~The green swine came, silent coward attacks, ~with bow and arrow, with sword and axe. ~They came for our blood, for our flesh to eat, ~We hacked them to death, our blades flaying their meat. ~ ~Though I have loved her, she still left this life, ~her pale white skin pierced by a goblin's bloody knife. ~But I am left here, an empty shell of a man. ~I cannot speak, the sorrow is more than I can stand. ~ ~Others drink themselves blind, but I cannot partake ~The others\tcelebrate, but smiles I can't fake. ~I will sit here by the fire and softly strum, ~only my lute knows the hollow man I have finally become.");
	say();
labelFunc063B_0327:
	if (!(var0000 == 0x00E0)) goto labelFunc063B_0341;
	message("~~ ~~The House of the Unicorn ~~ ~~By Gannt*");
	say();
	message("~Come! Enter into the rich house of the Unicorn. ~Open your ears and minds, ~Absorb the magic of the steed's fair horn! ~We are not now, ~nor never have we been ~Children of the Unicorn. ~But if we give in to ourselves, ~and listen to music of the elves ~one day soon we will be with the Unicorn.*");
	say();
	message("~On the day of thy birth ~came forth a new ray of sun to our earth ~Providing warmth and green riches ~to drive away the sorcery of witches. ~And we all take part in the gifts of the harvest moon, ~and give ourselves to the lute and the tune ~and drink the wealth of the early morning dew ~and savor the pleasure held by the precious chosen few.*");
	say();
	message("~Oh, to belong to the chosen of the Unicorn, ~The wealth of spirit, no fear of the forlorn. ~We can dance in the meadows by the whispering wonders, ~and ride forth on lightning and command the thunder. ~Oh, great steed, thou magical beast, ~in thine honor we break bread and feast. ~We raise our cups high in twilight's last never ~We are in the House of the Unicorn where we will dwell forever.");
	say();
labelFunc063B_0341:
	if (!(var0000 == 0x00E1)) goto labelFunc063B_0357;
	message("~~ ~~No Such Thing as Fairies ~~ ~~By Gannt*");
	say();
	message("~In our childhood years we learn that fairies glow, ~and this is good as everyone knows. ~But we partake the juice of the dark berries ~though we know there are no such thing as fairies... ~ ~We cry, though we rarely let it show, ~our tears fall like melting mountain snow. ~But still the fairies float like smoke rings though the night. ~stealing us blind with their mythical magical sight.*");
	say();
	message("~And with the fortune to seize priceless treasures, ~and the subsequent Moonshadian pleasures ~and as we grow older and bolder and drawn, ~the fairies visit us less till, alas, they are gone. ~ ~But for our offspring the fairies will still glow, ~and this is good as every child knows. ~But we keep partaking in the juice of the dark berries ~for we know that there are no such things as fairies...");
	say();
labelFunc063B_0357:
	if (!(var0000 == 0x00E2)) goto labelFunc063B_0381;
	message("~~ ~~DEVRA'S RECIPES~~ ~~*");
	say();
	message("Chicken and Rice~ ~ 2 cups rice~ 1 1/2 cups coarsely chopped green pepper~ 3/4 cup thinly sliced onions~ 3 tablespoons salad oil~ 1/4 cup cornstarch~ 2 cups chicken stock~ 3 tablespoons soy sauce~ 2 cups slivered cooked chicken~ 3 ripe tomatoes, cut in thin wedges~ ~ Cook green pepper and onions in oil till tender. Blend cornstarch and a little chicken stock. Add remaining stock and soy sauce. Gently stir chicken and stock into vegetables. Cook and stir until sauce is clear and thickened. Add tomatoes and cook just until heated. Serve over rice. Serves six.*");
	say();
	message("Broccoli Casserole~ ~ 1/2 stick butter~ 1 cup of rice, cooked~ 1 cup chopped onions~ 1 bunch broccoli, chopped~ 6 ounces of cream of mushroom soup~ 4 ounces of melted cheese~ ~ Melt butter in skillet; add chopped onion and saute until clear. Add the chopped broccoli. Stir thoroughly. Add the cream of mushroom soup. Stir and simmer a few minutes. Add 1 cup cooked rice; stir and simmer. If too thick, add a small amount of water and cook 25 to 30 minutes at 350 degrees.*");
	say();
	message("Apple Nut Squares~ ~ 3 eggs~ 1 3/4 cups sugar~ 1 cup cooking oil~ 2 teaspoons vanilla~ 2 cups flour~ 1 teaspoon salt~ 1 teaspoon baking soda~ 1 1/2 teaspoons cinnamon~ 2 cups peeled, diced apples~ 1/2 cup chopped pecans~ ~ Heat the oven to 325 degrees. Lightly grease a 9 by 13 inch pan. In large mixing bowl, combine first 8 ingredients; beat rapidly for 3 minutes (about 150 strokes). Stir in apples and pecans. Pour into prepared pan. Bake 50 to 60 minutes until toothpick inserted in center comes out clean. Serve with whipped\ttopping, ice cream, or as is, dusted with powdered sugar. Serves 12 to 15.*");
	say();
	message("Teatime Tassies~ ~ 3 ounces cream cheese~ 1/2 cup butter~ 1 cup sifted flour~ 3/4 cup brown sugar~ 1 tablespoon soft butter~ 1 teaspoon vanilla~ 1 egg~ dash of salt~ 2/3 cup broken almonds, or other nuts~ ~ Blend cream cheese and butter. Stir in flour. Chill 1 hour. Shape in 2 dozen 1\" balls. Form dough on bottom and sides of cups or muffin tins. Beat remaining ingredients together except nuts. Divide half of the nuts among the cups. Add egg mixture to top with remaining nuts. Bake at 325 degrees for 25 minutes.*");
	say();
	message("Saucy Franks~ ~ 1 lb. franks~ 2 tablespoons butter~ 10 3/4 oz. tomato soup~ 1/4 cup brown sugar~ 1/4 cup water~ 3 tablespoons vinegar~ 1 tablespoon worcestershire sauce~ 1/2 lemon, thinly sliced~ 1/2 onion, thinly sliced~ 1/4 cup chopped green pepper~ ~ ~ Score franks in corkscrew fashion. In skillet, brown franks lightly in butter. Add remaining ingredients except green pepper. Simmer covered 10 minutes. Add green pepper and cook 5 minutes longer.*");
	say();
	message("Peanut Butter Fudge~ ~ 2 cups sugar~ dash of salt~ 2/3 cup milk~ 1 tablespoon light syrup~ 2 tablespoons butter~ 1 cup peanut butter~ 1 teaspoon vanilla~ ~ ~ Mix first 4 ingredients and cook until soft ball stage. Add remaining ingredients and blend. Pour quickly into greased pan and cut into squares.*");
	say();
	message("Noodles~ ~ ~ 1 egg, beaten~ 1 teaspoon soft butter~ 1/2 teaspoon salt~ 2 tablespoons milk~ 1 teaspoon cider vinegar~ 1 cup flour~ ~ ~ Combine egg, butter, salt, milk, and vinegar. Add enough flour to make a stiff dough. Roll out very thin on floured surface. Let dough stand about 2 hours, until dried. Cut into strips. Drop noodles in salted water or broth. Cook for 10 minutes. Makes 3 cups of uncooked noodles.");
	say();
labelFunc063B_0381:
	if (!(var0000 == 0x00E3)) goto labelFunc063B_0397;
	message("~~ ~~TROUT SURPRISE~~ ~~By Jendon*");
	say();
	message("Pan Fried Whole Trout~ ~ Trout, 2 to 3 lbs. cleaned~ 2 tsp. salt~ 1/2 tsp. ground pepper~ 1/2 cup yellow cornmeal~ 1/2 cup flour~ 3 tbsp. butter~ 8 tbsp. vegetable oil~ 1 lemon, cut into wedges~*");
	say();
	message("Wash trout under cold water; pat dry with a towel. Sprinkle with salt and pepper. Mix cornmeal and flour. In heavy skillet, melt butter in oil over moderate heat. When the foam begins to subside, roll trout in cornmeal/flour mixture, shake off excess and put in skillet. Fry 4-5 minutes on each side, until golden brown and flaky. Serve with lemon wedges.");
	say();
labelFunc063B_0397:
	if (!(var0000 == 0x00E4)) goto labelFunc063B_03D1;
	message("~~ ~~GUIDE TO KNIGHTHOOD~~ ~~By Graeme of Monitor~~");
	say();
	message("Courage is in thine heart; if thine heart is not in danger of being pierced by a blade, then thou canst not fight with courage.*");
	say();
	message("Courageous men choose as weapons the sword, hammer, mace, and axe. Be wary of those who wield these weapons well, for they are fierce foes.~");
	say();
	message("Be also wary of those who weave spells, for they have no courage, and the cowardly weave webs of deceit, lies, and trickery.");
	say();
	message("Courage manifests itself on a battlefield, and the side whose courage is greatest, regardless of numbers, shall emerge victorious.~");
	say();
	message("A courageous man knows that one can leave the battlefield only two ways: By eliminating all of the enemies or in death.");
	say();
	message("A man whose life thou hast saved, or who hath saved thine, can be trusted the rest of thy life.~");
	say();
	message("A knight must never work toward personal goals in lieu of the goals of his Lord.~");
	say();
	message("Courage is not only taking sword up against his foe; it is the courage to admit to and remedy his own shortcomings, and if it happens that the knight is wrong, he must have the courage to admit as much.*");
	say();
	message("A knight must know, beyond the martial skills of the weapon of his fancy, the art of tactics, as it may some day come to him that the lives of his fellow knights may be decided by his tactical decisions.~");
	say();
	message("Any knight who betrays another will never be allowed to take up arms again. A knight who perpetrates such a wrongdoing is no knight; he is like unto the goblins he once warred against.~");
	say();
	message("Courage is separate from stupidity; there comes a time to run and regroup in some battles, but only those which are unwinnable.~");
	say();
labelFunc063B_03D1:
	if (!(var0000 == 0x00E5)) goto labelFunc063B_03F3;
	message("~~ ~~WARRIORS OF FORTUNE QUARTERLY~~ ~~The Adventurer's Guidebook~~ ");
	say();
	message("~\tFor you men who are stern of heart and gifted in the ways of weapons of steel, fortunes more mightier than you can dream of lie in your near future. All you must do is read the secrets held within these pages and you will be on the way to riches. Enter into mysteries that have baffled men through the ages, with rewards greater than those of today's kingdoms. Come, adventure and gold are on your horizon.*");
	say();
	message("~This issue offers the stern-hearted adventurer a chance to be the first to a miser's treasure! With more gold than ten ships can carry! Read on, and learn the history and the location of one of the world's richest lost lairs. Couldst thou be the first to find it? ~\tMany hundreds of years ago there was a miser named Triphako who had accumulated a massive fortune by swindling the local natives and by hiring pirates to attack his competitor's ships and cargo.*");
	say();
	message("~\tOne night after he had a vivid dream about losing his vast wealth, Triphako consulted a great wizard. The sage forewarned that the miser was about to lose all of his wealth in the near future and that nothing that he could do would prevent this. Thinking that he could avoid the prophecy, the miser took all of his gold to a cave in the northern icy reaches for safe storage. He hired the wizard to create a series of tunnels in the rear of the cave that no one could find their way through without a magical map. ~\tWhen all was finished, the wizard conjured an Ice Dragon to guard the mouth of the cave that led to the riches. On the voyage back to the palace, the miser, fearing that the wizard would allow his secret to be known, killed the wizard by pushing him into the sea.");
	say();
	message("~\tUnfortunately for him, upon the wizard's death, the magical map disappeared in a puff of blue smoke. Fearing that the prophecy had come true, the miser returned to the cave and tried to find the route to his riches. True to the wizard's warning, the miser never did reach his riches. Most say that he lies somewhere within the frozen caverns, for he never returned.");
	say();
	message("~\tTo this day no one hath survived the tunnels and reached the lair of the Ice Dragon. Some have attempted to face the Ice Dragons at the mouth of their cave, but all have either fled, or become permanent fixtures in the ice surrounding the cavern's mouth. ~\tIf thou beest brave, and sure of thy skills in battle, thou mayest find the secret way into the lair of Triphako and to his riches untold.");
	say();
labelFunc063B_03F3:
	if (!(var0000 == 0x00E6)) goto labelFunc063B_0415;
	message("~~ ~~THE RITES OF CREMATION~~ ~~by Tolbert~~");
	say();
	message("~\tLet this book serve as a guide to those who follow me in the honorable profession of cremator to the finest warriors in all the lands known to mankind, the fine fighters of Monitor!");
	say();
	message("\tMost of this will become known during thine apprenticeship, but these written words will serve to bolster that which thy predecessor will be teaching thee.~");
	say();
	message("\tThe most important thing thou canst learn of thy profession is this: being a cremator is no less honorable or worthy a duty than taking up sword and shield and doing battle with goblins, trolls, and all the other uncivilized fiends that populate our land. I put to any doubters this question: where would a warrior be if he knew that, should he die valiantly in battle, his body would not be brought back to receive a proper cremation? That his body, primed and trained for war in life, should feed the carrion cowards who would rather flee than fight, or perhaps a meal for the wives of those foul beings who struck him down? He would be in the rear of the force, hoping that he returns home; worried more for his life than guiding his blade through the hearts of his enemies.*");
	say();
	message("\tI have shown thee the worth of thy profession; now I will reveal to thee the import of burning one's body, as opposed to the primitive practice of burial. Thou hast known from the day thy first words were spoken that there is mystical power in the ashes of the dead. 'Tis true, and thou dost know this from thy Test of Knighthood. Ashes are the soul of a man; his spirit is locked within the remains of his lifeless body, and burning it releases the spirit from its imprisonment. If this is not done, the spirit will go insane and rise up as a monster -- lifeless, yet hateful and vengeful and animated. The spirit is in torment. This is no way for a courageous knight to spend eternity. For such a reason, the cremator is a respected and honored member of our stout city.~");
	say();
	message("\tThe question arises that, after the body is cremated (the method is described in detail in a later chapter), where must the ashes be stored? Fortune and wisdom on the part of our forefathers have placed us in a land whereby an opening in the great mountains to the west can serve as catacombs; a tomb for the courageous dead. It seems that these were once daemon lands, as evidenced by the ruins in the northwest, but more definitively by the catacombs. Therein, coffins and dusty tapestries hold their unburned dead. No doubt the place is naught but ruins because the maddened corpses did rise up and wreak their vengeance on the fools...");
	say();
labelFunc063B_0415:
	if (!(var0000 == 0x00E7)) goto labelFunc063B_042B;
	message("~~TEMPLES OF CHAOS~ Translated by Miggim*");
	say();
	message("~Xenka's prophecies mention the ancient Ophidian temples of Chaos as somehow being important to the Hero From Another World. Though I have not been able to decipher the true meaning of Xenka's visions regarding these temples, I feel that the Hero From Another World shall surely need some information regarding their location. I have translated a brief description of the Chaos temples from Ophidian script into Runic.*");
	say();
	message("The Temple of Emotion was carved from the living rock of Skullcrusher. To find the Temple of Emotion thou shouldst look for a small lake. The temple's entrance is a small distance south of this lake. The Temple of Enthusiasm lies along the coast, north of the great Spinebreaker mountains. The Temple of Tolerance was built near the coast at the northern end of the snowy valley between the Spinebreaker and Skullcrusher mountains.");
	say();
labelFunc063B_042B:
	if (!(var0000 == 0x00FA)) goto labelFunc063B_0453;
	message("~~ ~~Great Practical Jokes~~  ~~*");
	say();
	message("Chapter One: Exploding Books *");
	say();
	message("Heh, heh, heh.");
	say();
	var0001 = UI_execute_usecode_array(item, [(byte)0x23, (byte)0x55, 0x02C0]);
labelFunc063B_0453:
	return;
}


