#game "serpentisle"
void Func0282 shape#(0x282) ()
{
	var var0000;
	var var0001;
	var var0002;
	var var0003;
	var var0004;
	var var0005;

	if (!(event == 0x0001)) goto labelFunc0282_061E;
	UI_play_sound_effect2(0x005E, item);
	UI_book_mode(item);
	var0000 = UI_get_item_quality(item);
	if (!(var0000 == 0x0000)) goto labelFunc0282_0033;
	message("~~ ~~PHIL'S GUIDE TO UNFINISHED USECODE~~  ~~by Phil*");
	say();
	message("~~     An enlightening discourse on the enigma of usecode.");
	say();
	message("~Beginning with the heretofore unresolved mysteries of global variables...*Page 2*Page 3*Page 4*Page 5*Page 6*Page 7");
	say();
labelFunc0282_0033:
	if (!(var0000 == 0x0018)) goto labelFunc0282_0045;
	message("~~ ~~THE BOOK OF THE FELLOWSHIP~~ ~~by Batlin of Britain.*");
	say();
	message("     Good morning to thee, gentle friend and traveller! No matter what time of day it might be when thou art reading this -- no matter what the hour of the clock -- I say good morning to thee because this very moment brings to thee the coming of the dawn. The dawn, as everyone knows, is the moment when illumination comes. The dawn marks the end of the long dark night. It is the moment that marks a new beginning. It is mine humble hope that these words may be for thee a dawning, or at least, a sort of awakening...");
	say();
labelFunc0282_0045:
	if (!(var0000 == 0x0019)) goto labelFunc0282_0067;
	message("~~ ~~LORD BRITISH~~The biography of Britannia's longtime ruler~~ ~~ by K.Bennos*");
	say();
	message("     ...While many may remember that Lord British was once but one of eight monarchs (when the lands were known as Sosaria), few are aware that he is not even a native of our own lovely Britannia. His origin is from another world, one from which he entered ours by way of a red moongate. (In fact, it is through this same type of gate that the Avatar of legend purportedly enters Britannia.) As ruler of one of the eight kingdoms, he was instrumental in selecting a champion to face Mondain, Minax, and Exodus.~");
	say();
	message("     When the terrible machine, Exodus, was defeated, 'twas Lord British behind whom all the people of Sosaria rallied. The unified land become known as Britannia, with Lord British as the sole monarch. Never let it be said, though, that he rules with a tyrannical hand. His reign hath always been one of Truth, Love, and Courage, supported by his utmost belief in the eight virtues.~");
	say();
	message("     It was Lord British who had the insight to call forth a quest for the Avatar (who also happened to be the champion from the days of Sosaria), and who gave prosperity and happiness unto the people.~");
	say();
	message("     Then came his mysterious disappearance, when the Stranger who became the Avatar was called by his companions to aid in the search for the lost monarch. Note how Lord Blackthorn, affected by the Shadowlords, quickly turned Britannia's fair lands into a place of terror. But find our noble Lord the Avatar did, and Britannia was restored to its former, peaceful state.~");
	say();
	message("     Then came the gargoyles, and our honorable sovereign thoughtfully requested the return of the Avatar...");
	say();
labelFunc0282_0067:
	if (!(var0000 == 0x0027)) goto labelFunc0282_0085;
	message("~~ ~~THE APOTHECARY'S DESK REFERENCE~~ ~~by Fetoau*");
	say();
	message("     It is the author's expectation that thou art reading this to familiarize thyself with the effects of various potions based on their color. The first part of this work will discuss such aspects, with the remaining pages covering the materials and steps required to make such alchemical creations.*");
	say();
	message("     Definitions:~~Black potion: Drinking this will render the individual invisible for several minutes.~Blue potion: This mixture will put the imbiber into a deep sleep.~Orange potion: This potion will awaken an individual who was magically put to sleep.~Purple potion: This concoction will provide magical protection for several minutes of hard fighting.~White potion: This potion will provide a small bit of illumination, much like a candle, for a few minutes.~ Yellow potion: This powerful mixture will give healing aid to the imbiber's wounds.~~WARNING: Green potion: This potion is a dangerous toxin, and will poison the imbiber, possibly killing the individual.~ Red potion: This fabulous drink will cure most poisons, including those acquired from the slugs in the swamps and that gained from drinking a GREEN potion.");
	say();
	message("~Bluish Black potion: For thine adventures in the Icy Lands, that renowned concoction is critical in such climate. It is for thee to use in plenty for it will prevent thee from freezing to death.~Orange Shimmering potion: Specifically designed for the busy wizard whose lifestyle requires him or her to cast many a spell. Once this delectable potion is absorbed it will enable thee to cast many more spells.*");
	say();
	message("     This next section details how one can best recreate these uncanny concoctions...");
	say();
labelFunc0282_0085:
	if (!(var0000 == 0x002C)) goto labelFunc0282_009F;
	message("~~ ~~THE PROVISIONER'S GUIDE TO USEFUL EQUIPMENT~~ ~~by Dell*");
	say();
	message("     While most suppliers will rave about the effectiveness of a good sword or specially fitted armour, I personally feel that proper exploring gear is much more necessary.~");
	say();
	message("     Consider this, dear reader. While thou mightest happen to encounter a wild bear in thy travels, or, even less likely, a troll, thou art doubtless going to be in need of much more mundane equipment.~");
	say();
	message("     Wilt thou possibly be outside city walls when darkness comes? Then buy a torch. And how wilt thou carry thy provisions? A backpack will prove necessary. And what about a container for thy refreshment? Purchase a jug or bucket. As for...");
	say();
labelFunc0282_009F:
	if (!(var0000 == 0x002F)) goto labelFunc0282_00BD;
	message("~~ ~~WHAT COLOR IS THY BLADE? ~~ ~~by Menion*");
	say();
	message("The first step in effective sword-forging is to fill a crucible with metal. Then, with the bellows, the fire should be made extremely hot. When the flame no longer continues to grow in its glow, set the crucible on the fire to melt the metal.~");
	say();
	message("     Afterwards, pour the molten metal\tinto the blade mold and let it cool. Be warned! The crucible is at an extremely high temperature. Lift the cooled blade from the mold. Again heat up the fire and set the blade within. Be careful not to let it lose its shape. Set it in there only long enough for the blade to become malleable.~");
	say();
	message("     When it is ready, finish shaping it on the anvil with the hammer. When thou hast formed a blade of the desired shape, use the quenching barrel to cool the metal. It will harden quickly, so be sure the blade is as sharp as thou dost want it to be.~");
	say();
	message("     All that thou hast left to do now is to put the pommel over the tang. It will require hard work to make a fine, sturdy sword, but the finished weapon is well worth it!");
	say();
labelFunc0282_00BD:
	if (!(var0000 == 0x003D)) goto labelFunc0282_0147;
	message("~~ ~~JOURNAL OF THE KING~~ ~~OF THE WHITE DRAGON*");
	say();
	message("\t\tOn the Twelfth Day before the Solstice Festival:");
	say();
	message("~\t\tShamino, traitor, I will destroy thee as thou didst destroy my beloved daughter, Beatrix. Shamino, cursed be thy name, I befriended thee and thou didst betray me. I asked my people to help thee erect\tthy castle and betrayal is thine only response to them. Traitor!*");
	say();
	message("\t\tOn the Eleventh Day before the Solstice Festival:");
	say();
	message("~ \tDespair hath been the daily lot of my poor Beatrix. Now, I myself have my share of worries. I am surrounded by traitors and goblins are closing in on the castle. Shamino, doomed be thy name, I, King of the White Dragon, want to hang, draw and quarter thee.");
	say();
	message("My poor Beatrix was so joyful when thou didst request her hand from me. I agreed happily to such a union. My beloved daughter left me in order to live in thy new castle. By that time thou hadst already been touched by the obsession to foil Mondain from his conquest of the world. Thou didst leave on thy journey to seek the advice of Lord British, from hence never to return. The long-awaited wedding was never to be. My lovely child, my Beatrix, remained unwed waiting for her love to return. She loved thee and had faith in thee, Shamino, cursed be thine offspring.*");
	say();
	message("\t\tOn the Tenth Day before the Solstice Festival:");
	say();
	message("~\t\tThose goblins, I see those malformed goblins coming for us. They are destroying our wealth and our lives as Shamino, cursed be his name and his lineage, destroyed my Beatrix's health and life.");
	say();
	message("She died forlorn.");
	say();
	message("Thy treacherous heart led Beatrix to a lonely grave.*");
	say();
	message("On the Ninth Day before the Solstice Festival:");
	say();
	message("~\t\tThe Kingdom is plagued by hordes of goblins that grow more fierce and daring with each passing season. I am surrounded by traitors and should not trust anyone. What to do? Beatrix, thine adorable light no longer shines upon me. How solitary thou must be in thy cold bed. This year I will hold the grandest Solstice Festival ever. Thou wilt love it. 'Tis especially dedicated to thee, my right well beloved.*");
	say();
	message("\t\tOn the Eighth Day before the Solstice Festival:");
	say();
	message("~\tThose magic-warped goblins are everywhere and they are persistent.");
	say();
	message("They must be led by that villainous Shamino.");
	say();
	message("A man who doth not keep his word is less than a man. How couldst thou trust him, Beatrix.*");
	say();
	message("\t\tOn the Seventh Day before the Solstice Festival:");
	say();
	message("~\tShamino the deceitful and his allies are waiting in the dark passages of this castle to ambush me. I know it. I saw them in my dream last night.");
	say();
	message("They will not succeed. They cannot succeed for I have a plan to save my people from traitors and ravaging goblins. Beatrix, I will let thee know about this idea of mine, thou wilt be delighted...*");
	say();
	message("\t\tOn the Sixth Day before the Solstice Festival:");
	say();
	message("~\tMy dearest beloved one, how thou must long for company in thy misery.");
	say();
	message("This bacchanal will bring thee all of thy friends and our people. That villainous Shamino will have the fate he doth deserve.*");
	say();
	message("\t\tOn the Third Day before the Solstice Festival:");
	say();
	message("~\tI am looking forward to seeing thy Solstice Festival, yes, this season is thy Festival. I planned it for thee. And, indeed, for all of us.");
	say();
	message("\t\tTraitors and deceivers alike are in for a surprise. All of my subjects and myself -- we will not leave anything for the goblins to take.");
	say();
	message("\t\tTwo days hence....*");
	say();
	message("\t\tOn the Eve of the Solstice Festival:");
	say();
	message("All is prepared for my greatest bacchanal ever.");
	say();
	message("\t\tOn the morning of the Solstice Festival:");
	say();
	message("~\tBeatrix, soon we will be reunited and part never again.");
	say();
	message("This Solstice Festival will be recorded in the annals of the Kingdom of The White Dragon. It is to be the greatest feast ever!");
	say();
	message("Let us all rejoice in one night of revelry! After the midnight revels and before the end of the night, a new dawn will rise...");
	say();
labelFunc0282_0147:
	if (!(var0000 == 0x003E)) goto labelFunc0282_0189;
	message("~~ ~~ DIARY~~ ~~Anonymous*");
	say();
	message("\t\tI was hired by Batlin the first time we met, in Fawn. A recently shipwrecked pirate, I had escaped from the Storms as well as jail. Since then I have been in his service with no interruption nor reason to complain.");
	say();
	message("~Week 1:");
	say();
	message("Our first meeting was a strange one. I remember gazing around from the shores of the bay, climbing on top of a hill and seeing no signs of life. No signs of life for miles and miles around except in a spot in the middle of the bay where I perceived a shimmering city: Fawn. On my way downhill I ran into a group of men in which I recognized an old pirate friend of mine, Pilot. They were looking for manpower and I was available. Pilot introduced me to Batlin and I was in. We marched into Fawn where Batlin had some business to conduct.*");
	say();
	message("~Weeks later:");
	say();
	message("\t\tHow we got to this place, I am not certain, for I was blindfolded while we were in the doing of it. All I can say is that my master knows powerful magics, which allow us to step aside from the barriers of this physical world. Thus, I find myself in the frozen north, in the abandoned sanctuary of a long dead people. Here, we have slain a Beast of Ice, and captured a Daemon's Soul.");
	say();
	message("Soon after the Daemon was imprisoned, I beheld with anxious eyes a dreadful vortex. Believe me, I have seen many a storm on various seas and continents, but never ever such a fury. It is as if Nature herself is in contortion.");
	say();
	message("~~On the third day of the following week:");
	say();
	message("At the first streak of dawn, we travelled overland across the snowy wastes to the great mountains which my master calls the Peaks of Skullcrusher.");
	say();
	message("In the depths beneath the mountains, we sought another of these Daemons. This proved to be a difficult task. We had to keep a strict watch to discover him in his hiding place. Finally, we trapped the second prisoner, whose name is Anarchy.");
	say();
	message("We searched all over the Skullcrusher mountains for this bane.");
	say();
	message("~On the last day of the week:");
	say();
	message("Then, we travelled by magical means until we found ourselves in the tangled forest of the northlands. The last Daemon had eluded us in the Plains of Ice, but in his new form he was not so swift. Now his trail hath led us to this ruined castle.");
	say();
	message("I will finish this entry later tonight.");
	say();
labelFunc0282_0189:
	if (!(var0000 == 0x003F)) goto labelFunc0282_0317;
	message("LOVE SONNETS~~ by Beatrix~~");
	say();
	message("To the only begetter of these");
	say();
	message("\t\t\t\tsonnets");
	say();
	message("To the well-wishing adventurer");
	say();
	message("\t\t\tin setting forth...*");
	say();
	message("\t\t\t\tI~");
	say();
	message("Shamino, valiant adventurer,");
	say();
	message("Homo malicious");
	say();
	message("Adored from mine earliest hour,");
	say();
	message("Magnanimously, thy presence");
	say();
	message("     on all dost shower");
	say();
	message("Infinite love! By life thou dost");
	say();
	message("     devour,");
	say();
	message("Non-fading and delicious,");
	say();
	message("Our charming love, sweetest");
	say();
	message("     power.*");
	say();
	message("\t\t\t\tII~");
	say();
	message("My heart is a chest");
	say();
	message("Of bitterness");
	say();
	message("Since we are apart");
	say();
	message("A harness of teardrops");
	say();
	message("I fear lest");
	say();
	message("I should fall from some height");
	say();
	message("On my shoulder");
	say();
	message("The weight");
	say();
	message("In mine heart");
	say();
	message("The pain");
	say();
	message("Why wait?");
	say();
	message("Why explain?");
	say();
	message("Shamino");
	say();
	message("Dost thou not");
	say();
	message("Know");
	say();
	message("How to care?*");
	say();
	message("\t\t\t\tIII~");
	say();
	message("Since the War of Mondain");
	say();
	message("One memory I keep");
	say();
	message("When beyond these Realms");
	say();
	message("Thinking of us I weep");
	say();
	message("Is there one more");
	say();
	message("Chance to meet under");
	say();
	message("              the elms?*");
	say();
	message("\t\t\t\t IV~");
	say();
	message("Never this warrior's destiny");
	say();
	message("     allowed");
	say();
	message("His love to gain");
	say();
	message("Though restless, roving on");
	say();
	message("     adventure proud");
	say();
	message("He traversed oft the land");
	say();
	message("And oft the main");
	say();
	message("But love is like grain");
	say();
	message("It needs a tender hand");
	say();
	message("To grow, flourish and mature");
	say();
	message("The Wrath of Mondain");
	say();
	message("Destroyed our bond");
	say();
	message("Thy past thou shalt nurture");
	say();
	message("For greater future");
	say();
	message("In the worlds beyond*");
	say();
	message("\t\t\t\t V~");
	say();
	message("Sunset");
	say();
	message("Over the Main Gate");
	say();
	message("Going thy way");
	say();
	message("I stare at thee");
	say();
	message("Breathing in thy scent");
	say();
	message("I start the ascend");
	say();
	message("Hastily");
	say();
	message("Blasting thee with a spectral");
	say();
	message("     spell");
	say();
	message("I shimmer");
	say();
	message("Away.*");
	say();
	message("\t\t\t\t VI~");
	say();
	message("Beneath the yew");
	say();
	message("Thoughts of thee");
	say();
	message("Keep me warm and jolly");
	say();
	message("Raindrops like dew");
	say();
	message("On a lily's petal");
	say();
	message("Gently brushing my skin");
	say();
	message("Cleansing for the soul");
	say();
	message("What a delight");
	say();
	message("Never too soon");
	say();
	message("Watching my reflection");
	say();
	message("     in the river");
	say();
	message("As doth the Harvest Moon");
	say();
	message("Night after night");
	say();
	message("In this season.*");
	say();
	message("\t\t\t\t VII~");
	say();
	message("Shamino, shadows of thee");
	say();
	message("     appear");
	say();
	message("Before mine eyes all the year");
	say();
	message("I see the main road clear");
	say();
	message("Winding down to thy Castle");
	say();
	message("Where the winds whistle");
	say();
	message("There, at night I delight");
	say();
	message("At the magic sight");
	say();
	message("Of spectral spells like thunder");
	say();
	message("On thy neck, warrior");
	say();
	message("Thou shalt not");
	say();
	message("Abandon me.");
	say();
labelFunc0282_0317:
	if (!(var0000 == 0x0040)) goto labelFunc0282_0329;
	message("~~ ~~ My life~~ ~~by Yakka*");
	say();
	message("I grew up in a tiny village on the southern coast. Life hath been good so far and I know it will be longer than this book.");
	say();
labelFunc0282_0329:
	if (!(var0000 == 0x0043)) goto labelFunc0282_034B;
	message("MY RECORDS~~ by Vasculio~~");
	say();
	message("- One locket stolen from Frigidazzi, who refused to accept the passion I would have spent on her.");
	say();
	message("- The Living Scalp stolen from Filbercio, who sentenced me to die.");
	say();
	message("- The Spectral Orb stolen from Mortegro. I hate him, for he uncovered my dangerous research and betrayed me to the Council of Mages.*");
	say();
	message("- The Flux Analyzer stolen from Gustacio. Gustacio the influential, Gustacio the dignified, Gustacio the magisterial, I despise thee! I despise thee for thou representest everything I could never be.");
	say();
	message("- The Wand of Stone, taken from Torrissio. I blast mine hatred of Torrissio to the seven winds, for he was my partner in twisting the rules of the Mages, yet he abandoned me to their justice.");
	say();
labelFunc0282_034B:
	if (!(var0000 == 0x0044)) goto labelFunc0282_038D;
	message("MY JOURNAL by ~~Maleccio");
	say();
	message("\t\tI was born and raised in the city of Moonshade, a foe of Vasculio. Then I was taken to this place, where I am a prisoner of He Who Was Dead -- Vasculio.");
	say();
	message("Vasculio survives beyond death! He doth drink blood out of the living to keep himself alive. Hence his great thirst for fresh blood. His corpse is animated by means of spells and the Forbidden Reagent. I am his prisoner, fettered worse than a wild beast; manacled by mine hands and feet by day and by night. My blood is so vital to him that he is afraid I could break away. How could I in this cage. At times, I feel like survival is a meaningless word. I am exhausted. He hath been awakening me at all hours of the already too short night, thereby robbing me of mine all too brief night's slumber.*");
	say();
	message("\t\tThis week I managed to write more. I feel better than last month but still weak.");
	say();
	message("All through these interminable weeks in this cage, I have suffered from chronic weariness.");
	say();
	message("I do not believe escape is possible. I have seen Death face to face and she hath seen me. I am more than ever determined to continue to struggle for survival, for this is the primary instinct of the animal.*");
	say();
	message("The following week: I am losing track of time. I can track seven day periods but do not seem to recall any other relevant information; seasons and days are not part of my realm. Like life, they escape me. Am I less than an animal? This deranged mage, frantically seeking the lost secrets of Ophidian magic, certainly treats me as such. Actually, I do not feel anything anymore. I may live like an animal, but in my mind I am a man. I still think and write, therefore I exist. If this journal survives me and thou art reading it, regardless of the time elapsed, then I am alive. I am alive because my thoughts are alive.*");
	say();
	message("Today, fifth day of this present week, I am going to tell thee more about the twisted Vasculio.  He boasts that his magical powers are too great to be defeated by mere mortals. I have to tell thee that he was executed in Moonshade for practicing spells too diabolical for Man. His powerful magic allowed him to continue living as a liche.*");
	say();
	message("Also, I shall share this with thee, so that thou mayest make good use of it: Remember that no information hath value until thou dost test it.*");
	say();
	message("My words, hereunder, will guide thine understanding. Vasculio hath been experimenting with eternal life theories. Once, he stumbled upon a magic formula which, when used with the blood of an innocent, allowed a dead body to live longer. Moments before his execution he intoned the spell to keep his body living. Later he escaped from his coffin and travelled to Skullcrusher.*");
	say();
	message("Why Skullcrusher, thou askest? The answer is simply because he knew there was a second source for Stoneheart. Stoneheart is the prime ingredient of Bloodspawn, here in these caverns.");
	say();
	message("There is also another important reason. Vasculio knew that his enemies, the Mages of Moonshade, would never follow him here.*");
	say();
	message("Seventh day of the present week:");
	say();
	message("This undying sorcerer doth spend his time researching new spells. He is convinced that great magical secrets lie beyond the sealed entrances. He detects great power and magic in these areas. Vasculio hath not been able to locate the Grand Shrine within the great labyrinth beneath the Skullcrusher Peaks. I could tell thee that he stores provisions to support his allies, the man-eating Gwani. But this is not out of charity for them, for he also lives on with their blood. At this point I must stop writing for I can hear Vasculio howling in the tunnels. This is a sign that he is coming for me once more...");
	say();
labelFunc0282_038D:
	if (!(var0000 == 0x0045)) goto labelFunc0282_03CB;
	message("~~ ~~CURRICULUM~~ ~~by Vasculio*");
	say();
	message("As they lower me down to this");
	say();
	message("     hole in the ground");
	say();
	message("I scream for help, but they");
	say();
	message("     cannot hear a sound.");
	say();
	message("I scratch on this lid.");
	say();
	message("My fingers they bleed.");
	say();
	message("They plant me deep like");
	say();
	message("     an evil seed.");
	say();
	message("Now my bones decompose.");
	say();
	message("My flesh doth rot.");
	say();
	message("But soon I will rise and");
	say();
	message("     torture the lot");
	say();
labelFunc0282_03CB:
	if (!(var0000 == 0x0046)) goto labelFunc0282_0401;
	message("~~MINE EXPERIMENTS~~ ~~by Vasculio*");
	say();
	message("Day 1: \tThis is the dawn of a new era for me. I have been experimenting with eternal life for so long now. At last, I am seeing some results.~");
	say();
	message("Day 2: \tEntranced more Gwani in order to increase the number of my servants");
	say();
	message("Day 3: \tForced the Gwani to give to me the secret of entering certain passages. Experiments still in progress. A pint or two should keep me alive, depending on the frequency of transfusion.*");
	say();
	message("Day 8:\t        The lost secret of the Ophidians is within my reach, I can feel it. Ophidian magic will give to me absolute power.~");
	say();
	message("Day 12:        Last week I stumbled upon this magic formula which further lengthens the life span of a dead body. What a discovery! I need to use the mixture in an adequate proportion with the blood of an innocent.*");
	say();
	message("Day 17:        The caverns around Skullcrusher are filled with Stoneheart. More than I ever knew! I need as much Stoneheart as I may find since this is the prime ingredient of Bloodspawn. Stoneheart doth possess the red-orange glow of stalagmites. Once pulverized and mixed with fresh human blood it turns into a powerful magical reagent. Even though I have tried extremely powerful spells, Bloodspawn is easy and safe to transport. The mages who say otherwise are fools.*");
	say();
	message("Day 21:        This day I have spent researching many new spells. Exhausting. The prisoners in the cage may not live long enough to fulfill my plans. They seem to be weak.~");
	say();
	message("Day 28:        I am convinced that great magical secrets lie beyond the sealed entrances, for I sense great power and magic in the vicinity.*");
	say();
	message("Day 34:        Today is a sad day. My servants have failed me! While transporting Bloodspawn, they suffered simultaneous seizures and toppled into a chasm -- the Bloodspawn was lost!*");
	say();
	message("This is endangering my schedule. I need more workers. They must work longer hours. Toil is a necessity; sleep, an addiction from which they must be weaned.");
	say();
labelFunc0282_0401:
	if (!(var0000 == 0x0047)) goto labelFunc0282_0413;
	message("~~ ~~ Beyond The Sealed Entrances~~ ~~by Vasculio*");
	say();
	message("After all these years, I found two sealed entrances in the depths. I believe there is much to be discovered beyond these entrances, for they must have been sealed for a reason which doth go beyond mine understanding at this point in time. I have detected great power and magic in those areas. I presume that superior magical secrets lie beyond the sealed entrances.");
	say();
labelFunc0282_0413:
	if (!(var0000 == 0x0049)) goto labelFunc0282_0445;
	message("MY JOURNAL by Dolfo~~");
	say();
	message("\tThe Magic Gate hath not been easy to use. We had to search for the answer and it was only after much trial and error that we were able to determine that the key is a sequence of five colors.~");
	say();
	message("Red directly precedes White: Blue follows Yellow: Yellow directly follows Red: Yellow and White do not immediately follow one another.*");
	say();
	message("\tAs heretofore, the access to the doors of the Temple is blocked by a lock. The combination to this lock caused much commotion.");
	say();
	message("\tHerein is mine experience revealed to thee as it unfolded. Mark my words, for they will save thee much time.");
	say();
	message("I write the letters in our alphabet, but substitute the Serpent Runic letters to make thine understanding plain. I cannot write those cursed snake shapes.*");
	say();
	message("The runes must be placed left to right on the floor before the brass doors; any other placement will result in endless frustration.");
	say();
	message("I tried W.O.B. and C., none of the runes were in the right position.");
	say();
	message("I then tried C.B.W. and O.-- again, none of the runes were in the correct position.");
	say();
	message("I then tried the O rune in the first position, which was not where it belonged, and knew I could discern the puzzle...");
	say();
labelFunc0282_0445:
	if (!(var0000 == 0x004A)) goto labelFunc0282_045F;
	message("Memoirs~~ by Brother Markus*");
	say();
	message("\t\tIn the middle of a stormy night, a deafening roar of thunder tore apart the heavens and woke us. It was to be followed by five rapid and resounding knocks on the main door. I rose out of bed, donned my sandals and walked to the double doors. A desperate hand was pounding on the wooden frame. Most likely some belated traveller had been caught in the storm, I thought. As I half-opened the door, a swift streak of lightning pierced dramatically across the clouds, illuminating the darkness. Through the slashing rain appeared the figure of a bedraggled man, bedraggled yet with the certain stamp of nobility in his brow. Yet I did not recognize him.");
	say();
	message("He rushed in, looking for the hearth. Several of my brethren helped him with dry clothes and a hot beverage. He said his name was Blackthorn, and that he had come a long way to seek refuge in our monastery. He thanked us sincerely and then asked for hospitality, which we granted him.");
	say();
	message("He said that he was an exile from a land called Britannia, and that since his departure he had been roaming the seas in search of a haven. He stayed with us, at the Monastery, for some time. We taught him from the writings of Xenka, whence he learned that birth, ranks, titles, power and gold are meaningless, for this world is but a thoroughfare. We are all brought into this world equal in rights and we depart from it carrying nothing with us but our deeds, good and ill.");
	say();
labelFunc0282_045F:
	if (!(var0000 == 0x004B)) goto labelFunc0282_0485;
	message("MY DIARY~~ by Pendar*");
	say();
	message("Day 1:\tAlea jacta est! Departure for the daemons' stronghold, with all our worthy company. Finally, we are ready to pursue this campaign. We are going to erase these daemons from the face of the earth. Dungeon Furnace, thy time hath come, thou wilt burn! Our troops are marching into the caves. I am more relaxed after all those days of recruiting men.*");
	say();
	message("This is a strong army, as large as daybreak, whereby thou wilt observe the valor concealed in our noble hearts. Monitorian knights have never feared anything or anyone, certainly not daemons! I am confident in a swift victory for our side.*");
	say();
	message("Day 4:\t'Tis hot, with a stench like brimstone in the air. The mist doth have an unhealthy odor, and our limited supply of foods hath made us cautious. Wrapped in my bedroll by the fire, I slept soundly. So did most of our men. The battle hath been taking its toll on us all. In the morning, I rose at the sound of the war drums echoing in the distance. They kept coming. In brief, by one means or the other, our company was diminished.*");
	say();
	message("Day 7:  \tThe next move was to attack before daemons could form into a solid defense again. Lost two of my right best old stalwarts in a horrible manner. They walked too close to the pool and were taken by that horror in the pool. Knight, pity thy companions for they left for the abysmal depths of the unknown.*");
	say();
	message("Day 11:  \tTense and anxious times have fallen upon thee, Pendar. Burning as was the day, I broke out in a chill as I witnessed the company being decimated. What a slaughter! Darkness closed in upon us. For the last couple of days, I have not slept, though I am weary and tormented. I confess having scarcely closed mine eyes on any night this past week. The nights are sleepless and the days seem to be endless nights.*");
	say();
	message("Week 5:\tI saw a star in the caverns, large and bright. It was surely an omen. I rose and walked aimlessly; soon a peaceful feeling was to overcome me. At that moment, my self-confidence was higher than the sun in the sky. The lure of combat swept again through my veins, mine heart was pounding, I was ready to go into a decisive battle.");
	say();
labelFunc0282_0485:
	if (!(var0000 == 0x004C)) goto labelFunc0282_049F;
	message("~~ ~~THE SLEEPING BULL");
	say();
	message("~~ ~~Register*");
	say();
	message("~ ~Rodolfo of Moonshade~~Nakholy of Fawn~~Ensorcio of Moonshade~~Rishar of Monitor~~Batlin of Fawn~~Palos, manservant of Batlin*");
	say();
	message("~ ~Rodolfo of Moonshade~~Rishar of Monitor~~");
	say();
labelFunc0282_049F:
	if (!(var0000 == 0x004E)) goto labelFunc0282_055C;
	var0001 = "him";
	var0002 = "his";
	var0003 = "he";
	var0004 = "He";
	var0005 = "His";
	if (!UI_is_pc_female()) goto labelFunc0282_04EC;
	var0001 = "her";
	var0002 = "her";
	var0003 = "she";
	var0004 = "She";
	var0005 = "Her";
labelFunc0282_04EC:
	message("THE BOOK OF PROPHECIES~~ by Xenka*");
	say();
	message("\t\tWhen a stranger sojourns with thee in thy land, thou shalt not do him or her wrong. The stranger who sojourns with thee shall be to thee as the native among ye. And thou shalt love him or her as thyself; for I see the advent of a Hero From Another World who would unite the Serpents and save the world.*");
	say();
	message("I see the rocks in motion, and trees bursting open -- I see treasures which have lain hidden for centuries coming forth. There I see one which is of three. It is black. It is magic.");
	say();
	message("\t\tClearly do I see a Hero From Another World, but let it be said that ");
	message(var0003);
	message(" is not alone. ");
	message(var0004);
	message(" must not advance as one alone! I pray thee above all things to have this in remembrance. ");
	message(var0004);
	message(" must be accompanied by The Three.*");
	say();
	message("\t\tThe Hero From Another World will succeed through the use of powerful magic, the aid of specters, and the implements three of the Hierophant.*");
	say();
	message("\t\tMy words shed light upon darkness. Follow the unfolding of my words and thou wilt see that the friends of the Hero shall be ");
	message(var0002);
	message(" enemies. Visions shall make ");
	message(var0001);
	message(" wiser than ");
	message(var0002);
	message(" enemies, for thus is it always with ");
	message(var0001);
	message(".");
	say();
	message("The Hero From Another World must triumph even in ");
	message(var0002);
	message(" Dreams.*");
	say();
	message("The dead shall aid ");
	message(var0001);
	message(", but enemies among the living shall abound.");
	say();
	message("A careful choice of ally is necessary to ensure success. The Hero From Another World will even need a thief and a braggart as ");
	message(var0002);
	message(" ally.");
	say();
	message("I see the future as through a veil -- ");
	message(var0003);
	message(" shall be allied with those once ");
	message(var0002);
	message(" enemies, and shall find good men in bad company. I see the color red, and a woman is involved.");
	say();
labelFunc0282_055C:
	if (!(var0000 == 0x004F)) goto labelFunc0282_057E;
	message("Day 8 -- This rotten place ain't for me. It don't seem possible to revel around here.");
	say();
	message("Day 9 -- Did some work for Batlin. He thinks too much of hisself. I wish he'd fall off a cliff.");
	say();
	message("Day 12 -- Why did I ever leave Britannia?");
	say();
	message("Day 20 -- Batlin better pay me in gold or I'll be teachin' him");
	say();
	message("a lesson.");
	say();
	message("Gold is the only way for me to leave this bilgehole and have some fun in Britannia. Already know what I'll be buyin'! Buccaneer's Den is my idea of a good place to be!");
	say();
labelFunc0282_057E:
	if (!(var0000 == 0x0050)) goto labelFunc0282_05A0;
	message("~~ ~~ MY JOURNAL ~~ ~~by Silverpate*");
	say();
	message("Day 3 of Week 9:~~Today, I had another argument with Erstam, that old crazy mage with a foul temper! I could never stand him, I never will. Who doth he think he is? Erstam and I are so different that we simply cannot work together.*");
	say();
	message("Day 4 of Week 9:~~My precious Jawbone, I am so glad thou art mine, I use thee often and often again and still have no grounds to complain. What would I do without thee, tell me? Erstam, thou art not the only one who can travel through the Void!*");
	say();
	message("Day 7 of Week 9:~~Thy magic telescope is merely another trick thou hadst divined when thou didst fear my powers. Useless piece of equipment for a crazy old mage. I am tired of thee. I understand why Drogeni never came back...~");
	say();
	message("Thou art looking for immortality and will end alone, Erstam!~");
	say();
	message("I, Silverpate, will prove thee wrong. I will discover the solution relevant to our matters.");
	say();
labelFunc0282_05A0:
	if (!(var0000 == 0x0053)) goto labelFunc0282_05B6;
	message("~~ ~WEAVING~~ ~~by Carlyn*");
	say();
	message("     This is a complete sourcebook for a variety of patterns. Included are patterns for clothing, blankets, quilts, and sheets. The introduction even includes a section on weaving one's own cloth.~");
	say();
	message("     ...take the bale of wool and spin it on the wheel to make the thread. Once that is done, warp the thread across the loom and begin weaving. Shortly thou wilt have a nice length of cloth from which canst make a variety of useful things. For variation, use different colored threads on the loom to create exciting patterns.");
	say();
labelFunc0282_05B6:
	if (!(var0000 == 0x005A)) goto labelFunc0282_05D4;
	message("~~ ~~THE BLACK COMPENDIUM ~~ ~~Written by Mondain, with annotations by the enchantress Minax and magical formulae by the hellspawn Exodus.*");
	say();
	message("     To extend one's life is a complicated procedure, taking years to complete. However, there is an additional side effect: invulnerability. I have broken this work down into chapters based on each individual ritual. It is very important that these steps be performed in the order presented.*");
	say();
	message("     First, thou must procure five stones of the dust of crushed rubies. This must be mixed thoroughly with the ooze of a slime, enough to make the rubies into a thick paste. After thou hast created the paste, set it in an ivory jar and place the entire container in a bucket of olive oil for three years.*");
	say();
	message("     The next step is to procure 10 newborn babes, none more than six days old. With a knife cut from the bone of a harpy, thou must remove the blood from each newborn. To be kept fresh, the blood must be stored in an onyx flask, though mixing of each baby's blood is quite permissible.*");
	say();
	message("     Now thou shalt seek out...");
	say();
labelFunc0282_05D4:
	if (!(var0000 == 0x005B)) goto labelFunc0282_05EE;
	message("~~ ~~BROMMER'S FLORA~~ ~~by Brommer*");
	say();
	message("     This large tome describes most of the common plants indigenous to Britannia.~~");
	say();
	message("  ...The Greer plant is especially fascinating, for it spends most of its life huddled with its leaves wrapped in a tight ball. However, every so often, the leaves will unfurl, radiating out from the stem...*");
	say();
	message("  ...The Reaper is unique in that it is both plant and animal. Resembling a large tree, the Reaper is capable of self-animation as well as self-locomotion. Reapers have been known to attack those who cause harm to their home (i.e., the forests), but seldom reveal themselves otherwise...");
	say();
labelFunc0282_05EE:
	if (!(var0000 == 0x005C)) goto labelFunc0282_0608;
	message("~~ ~~BROMMER'S FAUNA~~ ~~by Brommer*");
	say();
	message("     Betwixt the covers of this book can be found details on the most prevalent animals that inhabit the lands of Britannia.~~");
	say();
	message("  ...Deer are quite prevalent in the forested areas of Britannia. They are shy creatures, generally shunning the presence of man, whom they know hunt them. Atop their head sits a pair of antlers...*");
	say();
	message("  ...The fox is a small animal, akin to a dog or a wolf. It is an omnivore, and more than willing to make do with a farmer's chicken when it tires of other foods...");
	say();
labelFunc0282_0608:
	if (!(var0000 == 0x0062)) goto labelFunc0282_061E;
	message("~~ ~~BIRDS OF BRITANNIA~~ ~~by Brother Wayne*");
	say();
	message("     Bound here is the comprehensive guide to the avian species, beautifully and colorfully illustrated by many different artists.");
	say();
	message("     ...Surprising to many is that the Silver-Winged Pharcelot is not the most prevalent bird in Britannia, though it is arguably the most visible. Far more popular is the Black-Tipped Grackle, but its predilection for dark, cool areas makes it considerably less visible.");
	say();
labelFunc0282_061E:
	return;
}


